// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"reflect"
)

// ApplyOperation applies a single operation to Fleet efficiently.
func (t *Fleet) ApplyOperation(op deep.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.EvaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.EvaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Fleet); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(deep.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/devices", "/Devices":
		if op.Kind == deep.OpLog {
			deep.Logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Devices)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(map[DeviceID]string); !ok || !deep.Equal(t.Devices, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Devices)
			}
		}
		if v, ok := op.New.(map[DeviceID]string); ok {
			t.Devices = v
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Fleet) Diff(other *Fleet) deep.Patch[Fleet] {
	p := deep.NewPatch[Fleet]()
	if other.Devices != nil {
		for k, v := range other.Devices {
			if t.Devices == nil {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: fmt.Sprintf("/devices/%v", k), New: v})
				continue
			}
			if oldV, ok := t.Devices[k]; !ok || v != oldV {
				kind := deep.OpReplace
				if !ok {
					kind = deep.OpAdd
				}
				p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: fmt.Sprintf("/devices/%v", k), Old: oldV, New: v})
			}
		}
	}
	if t.Devices != nil {
		for k, v := range t.Devices {
			if other.Devices == nil || !contains(other.Devices, k) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: fmt.Sprintf("/devices/%v", k), Old: v})
			}
		}
	}

	return p
}

func (t *Fleet) EvaluateCondition(c deep.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.EvaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Fleet) Equal(other *Fleet) bool {
	if len(t.Devices) != len(other.Devices) {
		return false
	}
	for k, v := range t.Devices {
		vOther, ok := other.Devices[k]
		if !ok {
			return false
		}
		if v != vOther {
			return false
		}
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Fleet) Copy() *Fleet {
	res := &Fleet{}
	if t.Devices != nil {
		res.Devices = make(map[DeviceID]string)
		for k, v := range t.Devices {
			res.Devices[k] = v
		}
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface ||
			rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
