/**
 * Produce and apply `deep` patches from JavaScript.
 *
 * This is the JavaScript half of github.com/brunoga/deep: the same patch wire
 * format, so a Go server and a browser can send each other changes rather
 * than whole documents. The format is specified in docs/wire-patch.md, and
 * this implementation is checked against a conformance corpus generated by
 * the Go one.
 *
 * ```ts
 * import { diff, applyPatch, reverse } from '@brunoga/deep-patch';
 *
 * const patch = diff(before, after);        // send this
 * const result = applyPatch(replica, patch); // on the other side
 * applyPatch(replica, reverse(patch));       // and undo it
 * ```
 *
 * The CRDT half is here too, for text several people edit at once:
 *
 * ```ts
 * import { connect } from '@brunoga/deep-patch';
 *
 * const room = await connect({ url: 'ws://host/ws?room=notes', node: 'ana' });
 * room.onUpdate(() => render(room.text));
 * room.insert(0, 'typing');
 * ```
 */

export type {
  ApplyResult,
  Condition,
  KeySchema,
  OpKind,
  Operation,
  Outcome,
  OutcomeStatus,
  Patch,
} from './types.ts';

export { applyPatch, GuardNotMetError, PathNotAllowedError } from './apply.ts';
export type { ApplyOptions } from './apply.ts';
export { diff } from './diff.ts';
export type { DiffOptions } from './diff.ts';
export { reverse } from './reverse.ts';
export { merge } from './merge.ts';
export type { ConflictResolver } from './merge.ts';
export { evaluate, checkType } from './conditions.ts';
export { equal, clone } from './equal.ts';
// The CRDT half: a collaborative document, presence, and the websocket
// client that keeps them in step with a Go hub.
export { Document } from './crdt/document.ts';
export { Awareness } from './crdt/awareness.ts';
export type { AwarenessEntry, AwarenessUpdate, AwarenessOptions } from './crdt/awareness.ts';
export { Clock } from './crdt/hlc.ts';
export type { HLC } from './crdt/hlc.ts';
export type { DeletedRange, StateVector, TextRun, Update } from './crdt/types.ts';
export {
  decodeStateVector,
  decodeUpdate,
  encodeStateVector,
  encodeUpdate,
  fromHex,
  toHex,
} from './crdt/binary.ts';
export { connect, Room } from './ws.ts';
export type { ConnectOptions } from './ws.ts';

export {
  buildPath,
  encloses,
  escapeKey,
  lastToken,
  parentPath,
  parsePath,
  removeAt,
  resolve,
  setAt,
  unescapeKey,
} from './path.ts';
