/**
 * Produce and apply `deep` patches from JavaScript.
 *
 * This is the JavaScript half of github.com/brunoga/deep: the same patch wire
 * format, so a Go server and a browser can send each other changes rather
 * than whole documents. The format is specified in docs/wire-patch.md, and
 * this implementation is checked against a conformance corpus generated by
 * the Go one.
 *
 * ```ts
 * import { diff, applyPatch, reverse } from '@brunoga/deep-patch';
 *
 * const patch = diff(before, after);        // send this
 * const result = applyPatch(replica, patch); // on the other side
 * applyPatch(replica, reverse(patch));       // and undo it
 * ```
 */

export type {
  ApplyResult,
  Condition,
  KeySchema,
  OpKind,
  Operation,
  Outcome,
  OutcomeStatus,
  Patch,
} from './types.ts';

export { applyPatch, GuardNotMetError, PathNotAllowedError } from './apply.ts';
export type { ApplyOptions } from './apply.ts';
export { diff } from './diff.ts';
export type { DiffOptions } from './diff.ts';
export { reverse } from './reverse.ts';
export { merge } from './merge.ts';
export type { ConflictResolver } from './merge.ts';
export { evaluate, checkType } from './conditions.ts';
export { equal, clone } from './equal.ts';
export {
  buildPath,
  encloses,
  escapeKey,
  lastToken,
  parentPath,
  parsePath,
  removeAt,
  resolve,
  setAt,
  unescapeKey,
} from './path.ts';
