// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"reflect"
	"regexp"

	v5 "github.com/brunoga/deep/v5"
)

// ApplyOperation applies a single operation to Stock efficiently.
func (t *Stock) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Stock); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/sku", "/SKU":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.SKU)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.SKU != op.Old.(string) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.SKU)
			}
		}
		if v, ok := op.New.(string); ok {
			t.SKU = v
			return true, nil
		}
	case "/q", "/Quantity":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Quantity)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.Quantity != op.Old.(int) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Quantity)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Quantity = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Quantity = int(f)
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Stock) Diff(other *Stock) v5.Patch[Stock] {
	p := v5.NewPatch[Stock]()
	if t.SKU != other.SKU {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/sku",
			Old:  t.SKU,
			New:  other.SKU,
		})
	}
	if t.Quantity != other.Quantity {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/q",
			Old:  t.Quantity,
			New:  other.Quantity,
		})
	}
	return p
}

func (t *Stock) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.evaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/sku", "/SKU":
		switch c.Op {
		case "==":
			return t.SKU == c.Value.(string), nil
		case "!=":
			return t.SKU != c.Value.(string), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.SKU)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.SKU))
		case "type":
			return checkType(t.SKU, c.Value.(string)), nil
		}
	case "/q", "/Quantity":
		switch c.Op {
		case "==":
			return t.Quantity == c.Value.(int), nil
		case "!=":
			return t.Quantity != c.Value.(int), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.Quantity)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Quantity))
		case "type":
			return checkType(t.Quantity, c.Value.(string)), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Stock) Equal(other *Stock) bool {
	if t.SKU != other.SKU {
		return false
	}
	if t.Quantity != other.Quantity {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Stock) Copy() *Stock {
	res := &Stock{
		SKU:      t.SKU,
		Quantity: t.Quantity,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface || rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
