// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"reflect"
	"regexp"
)

// ApplyOperation applies a single operation to Stock efficiently.
func (t *Stock) ApplyOperation(op deep.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.EvaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.EvaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Stock); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(deep.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/sku", "/SKU":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.SKU)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.SKU != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.SKU)
			}
		}
		if v, ok := op.New.(string); ok {
			t.SKU = v
			return true, nil
		}
	case "/q", "/Quantity":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.Quantity)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			_oldOK := false
			if _oldV, ok := op.Old.(int); ok {
				_oldOK = t.Quantity == _oldV
			}
			if !_oldOK {
				if _oldF, ok := op.Old.(float64); ok {
					_oldOK = float64(t.Quantity) == _oldF
				}
			}
			if !_oldOK {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Quantity)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Quantity = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Quantity = int(f)
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Stock) Diff(other *Stock) deep.Patch[Stock] {
	p := deep.NewPatch[Stock]()
	if t.SKU != other.SKU {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/sku", Old: t.SKU, New: other.SKU})
	}
	if t.Quantity != other.Quantity {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/q", Old: t.Quantity, New: other.Quantity})
	}

	return p
}

func (t *Stock) EvaluateCondition(c deep.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.EvaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.EvaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.EvaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/sku", "/SKU":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.SKU, c.Value.(string)), nil
		}
		if c.Op == "log" {
			deep.Logger().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.SKU)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.SKU))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field SKU")
		}
		switch c.Op {
		case "==":
			return t.SKU == _sv, nil
		case "!=":
			return t.SKU != _sv, nil
		case ">":
			return t.SKU > _sv, nil
		case "<":
			return t.SKU < _sv, nil
		case ">=":
			return t.SKU >= _sv, nil
		case "<=":
			return t.SKU <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.SKU == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.SKU == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/q", "/Quantity":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Quantity, c.Value.(string)), nil
		}
		if c.Op == "log" {
			deep.Logger().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Quantity)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Quantity))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Quantity")
		}
		_fv := float64(t.Quantity)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Quantity == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Quantity == iv {
							return true, nil
						}
					case float64:
						if float64(t.Quantity) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Stock) Equal(other *Stock) bool {
	if t.SKU != other.SKU {
		return false
	}
	if t.Quantity != other.Quantity {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Stock) Copy() *Stock {
	res := &Stock{
		SKU:      t.SKU,
		Quantity: t.Quantity,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface ||
			rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
