// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	gen "github.com/brunoga/deep/v5/gen"
	"log/slog"
	"reflect"
	"regexp"
)

// Patch applies p to t using the generated fast path.
func (t *Item) Patch(p deep.Patch[Item], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Item) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Item); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Item); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/sku", "/SKU":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.SKU == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.SKU, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.SKU)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.SKU = v
				return true, nil
			}
		}
	case "/q", "/Quantity":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Quantity == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Quantity, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Quantity)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Quantity = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Quantity = int(f)
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Item) Diff(other *Item) deep.Patch[Item] {
	p := deep.Patch[Item]{}
	if t.SKU != other.SKU {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/sku", Old: t.SKU, New: other.SKU})
	}
	if t.Quantity != other.Quantity {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/q", Old: t.Quantity, New: other.Quantity})
	}

	return p
}

func (t *Item) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/sku", "/SKU":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.SKU, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.SKU))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field SKU")
		}
		switch c.Op {
		case "==":
			return t.SKU == _sv, nil
		case "!=":
			return t.SKU != _sv, nil
		case ">":
			return t.SKU > _sv, nil
		case "<":
			return t.SKU < _sv, nil
		case ">=":
			return t.SKU >= _sv, nil
		case "<=":
			return t.SKU <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.SKU == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.SKU == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/q", "/Quantity":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Quantity, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Quantity))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Quantity")
		}
		_fv := float64(t.Quantity)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Quantity == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Quantity == iv {
							return true, nil
						}
					case float64:
						if float64(t.Quantity) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Item) Equal(other *Item) bool {
	if t.SKU != other.SKU {
		return false
	}
	if t.Quantity != other.Quantity {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Item) Clone() *Item {
	res := &Item{
		SKU:      t.SKU,
		Quantity: t.Quantity,
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *Inventory) Patch(p deep.Patch[Inventory], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Inventory) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Inventory); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Inventory); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/items", "/Items":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]Item); ok {
				_match = deep.Equal(t.Items, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Items, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Items)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.([]Item); ok {
				t.Items = v
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Inventory) Diff(other *Inventory) deep.Patch[Inventory] {
	p := deep.Patch[Inventory]{}
	{
		if (t.Items == nil) != (other.Items == nil) {
			p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/items", Old: t.Items, New: other.Items})
		} else {
			otherByKey := make(map[any]int)
			for i, v := range other.Items {
				otherByKey[v.SKU] = i
			}
			for _, v := range t.Items {
				if _, ok := otherByKey[v.SKU]; !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: "/items/" + deep.EscapePathKey(fmt.Sprintf("%v", v.SKU)), Old: v})
				}
			}
			tByKey := make(map[any]int)
			for i, v := range t.Items {
				tByKey[v.SKU] = i
			}
			for j := range other.Items {
				i, ok := tByKey[other.Items[j].SKU]
				if !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: "/items/" + deep.EscapePathKey(fmt.Sprintf("%v", other.Items[j].SKU)), New: other.Items[j]})
					continue
				}
				prefix := "/items/" + deep.EscapePathKey(fmt.Sprintf("%v", other.Items[j].SKU))
				sub := t.Items[i].Diff(&other.Items[j])
				for _, op := range sub.Operations {
					if op.Path == "" || op.Path == "/" {
						op.Path = prefix
					} else {
						op.Path = prefix + op.Path
					}
					p.Operations = append(p.Operations, op)
				}
			}
		}
	}

	return p
}

func (t *Inventory) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Inventory) Equal(other *Inventory) bool {
	if len(t.Items) != len(other.Items) {
		return false
	}
	for i := range t.Items {
		if !t.Items[i].Equal(&other.Items[i]) {
			return false
		}
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Inventory) Clone() *Inventory {
	res := &Inventory{}
	if t.Items != nil {
		res.Items = make([]Item, len(t.Items))
		for i := range t.Items {
			res.Items[i] = *t.Items[i].Clone()
		}
	}
	return res
}
