// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"reflect"
	"regexp"
	"strings"

	v5 "github.com/brunoga/deep/v5"
)

// ApplyOperation applies a single operation to Event efficiently.
func (t *Event) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Event); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/name", "/Name":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Name)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.Name != op.Old.(string) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Name = v
			return true, nil
		}
	case "/when", "/When":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.When)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			// Complex strict check skipped in prototype
		}
		if v, ok := op.New.(CustomTime); ok {
			t.When = v
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/when/") {
			op.Path = op.Path[len("/when/")-1:]
			return (&t.When).ApplyOperation(op)
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Event) Diff(other *Event) v5.Patch[Event] {
	p := v5.NewPatch[Event]()
	if t.Name != other.Name {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/name",
			Old:  t.Name,
			New:  other.Name,
		})
	}
	subWhen := (&t.When).Diff(&other.When)
	for _, op := range subWhen.Operations {
		if op.Path == "" || op.Path == "/" {
			op.Path = "/when"
		} else {
			op.Path = "/when" + op.Path
		}
		p.Operations = append(p.Operations, op)
	}
	return p
}

func (t *Event) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.evaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/name", "/Name":
		switch c.Op {
		case "==":
			return t.Name == c.Value.(string), nil
		case "!=":
			return t.Name != c.Value.(string), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.Name)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Name))
		case "type":
			return checkType(t.Name, c.Value.(string)), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Event) Equal(other *Event) bool {
	if t.Name != other.Name {
		return false
	}
	if !(&t.When).Equal((&other.When)) {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Event) Copy() *Event {
	res := &Event{
		Name: t.Name,
	}
	res.When = *(&t.When).Copy()
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface || rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
