// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/brunoga/deep/v5"
	"strings"
)

// ApplyOperation applies a single operation to Event efficiently.
func (t *Event) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Event); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/name", "/Name":
		if v, ok := op.New.(string); ok {
			t.Name = v
			return true, nil
		}
	case "/when", "/When":
		if v, ok := op.New.(CustomTime); ok {
			t.When = v
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/when/") {
			if (&t.When) != nil {
				op.Path = op.Path[len("/when/")-1:]
				return (&t.When).ApplyOperation(op)
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Event) Diff(other *Event) v5.Patch[Event] {
	p := v5.NewPatch[Event]()
	if t.Name != other.Name {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/name",
			Old:  t.Name,
			New:  other.Name,
		})
	}
	if (&t.When) != nil && &other.When != nil {
		subWhen := (&t.When).Diff(&other.When)
		for _, op := range subWhen.Operations {
			if op.Path == "" || op.Path == "/" {
				op.Path = "/when"
			} else {
				op.Path = "/when" + op.Path
			}
			p.Operations = append(p.Operations, op)
		}
	}
	return p
}

func (t *Event) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Path {
	case "/name", "/Name":
		switch c.Op {
		case "==":
			return t.Name == c.Value.(string), nil
		case "!=":
			return t.Name != c.Value.(string), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Event) Equal(other *Event) bool {
	if t.Name != other.Name {
		return false
	}
	if ((&t.When) == nil) != ((&other.When) == nil) {
		return false
	}
	if (&t.When) != nil && !(&t.When).Equal((&other.When)) {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Event) Copy() *Event {
	res := &Event{
		Name: t.Name,
	}
	if (&t.When) != nil {
		res.When = *(&t.When).Copy()
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
