// Commandpost's external face: the incident as a protobuf message, for
// consumers that are not this codebase — a dashboard in another language, a
// bot on the other side of an RPC boundary.
//
// The Go model (../model) is the source of truth; this schema mirrors it
// field for field. Deep's proto companion diffs and patches these messages
// through the protobuf runtime itself, so a consumer holding two snapshots
// can recover exactly what changed — including tasks matched by id, once the
// repeated field's key is registered.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: incident.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Task) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Task) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Incident struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 1 is the worst; matches model.Severity.
	Severity int32 `protobuf:"varint,3,opt,name=severity,proto3" json:"severity,omitempty"`
	// open | mitigated | resolved | closed.
	Status    string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Commander string   `protobuf:"bytes,5,opt,name=commander,proto3" json:"commander,omitempty"`
	Services  []string `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	// Addresses in their string form, as the netip family renders them.
	Hosts         []string               `protobuf:"bytes,7,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,8,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Updated       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{1}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Incident) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Incident) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Incident) GetCommander() string {
	if x != nil {
		return x.Commander
	}
	return ""
}

func (x *Incident) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Incident) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Incident) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Incident) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

var File_incident_proto protoreflect.FileDescriptor

const file_incident_proto_rawDesc = "" +
	"\n" +
	"\x0eincident.proto\x12\vcommandpost\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"\x93\x02\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\x05R\bseverity\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tcommander\x18\x05 \x01(\tR\tcommander\x12\x1a\n" +
	"\bservices\x18\x06 \x03(\tR\bservices\x12\x14\n" +
	"\x05hosts\x18\a \x03(\tR\x05hosts\x12'\n" +
	"\x05tasks\x18\b \x03(\v2\x11.commandpost.TaskR\x05tasks\x124\n" +
	"\aupdated\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aupdatedB.Z,github.com/brunoga/deep/examples/incident/pbb\x06proto3"

var (
	file_incident_proto_rawDescOnce sync.Once
	file_incident_proto_rawDescData []byte
)

func file_incident_proto_rawDescGZIP() []byte {
	file_incident_proto_rawDescOnce.Do(func() {
		file_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)))
	})
	return file_incident_proto_rawDescData
}

var file_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_incident_proto_goTypes = []any{
	(*Task)(nil),                  // 0: commandpost.Task
	(*Incident)(nil),              // 1: commandpost.Incident
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_incident_proto_depIdxs = []int32{
	0, // 0: commandpost.Incident.tasks:type_name -> commandpost.Task
	2, // 1: commandpost.Incident.updated:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_incident_proto_init() }
func file_incident_proto_init() {
	if File_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_incident_proto_goTypes,
		DependencyIndexes: file_incident_proto_depIdxs,
		MessageInfos:      file_incident_proto_msgTypes,
	}.Build()
	File_incident_proto = out.File
	file_incident_proto_goTypes = nil
	file_incident_proto_depIdxs = nil
}
