// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	"log/slog"
	"reflect"
	"regexp"
)

// Patch applies p to t using the generated fast path.
func (t *Account) Patch(p deep.Patch[Account], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Account) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Account); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Account); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/owner", "/Owner":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Owner == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Owner, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Owner)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Owner = v
				return true, nil
			}
		}
	case "/balance", "/Balance":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(float64); ok {
				_match = t.Balance == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Balance, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Balance)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(float64); ok {
				t.Balance = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Balance = float64(f)
				return true, nil
			}
		}
	case "/late_fee", "/LateFee":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(float64); ok {
				_match = t.LateFee == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.LateFee, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.LateFee)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(float64); ok {
				t.LateFee = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.LateFee = float64(f)
				return true, nil
			}
		}
	case "/status", "/Status":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Status == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Status, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Status)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Status = v
				return true, nil
			}
		}
	case "/last_seen", "/LastSeen":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.LastSeen == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.LastSeen, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.LastSeen)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.LastSeen = v
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Account) Diff(other *Account) deep.Patch[Account] {
	p := deep.Patch[Account]{}
	if t.Owner != other.Owner {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/owner", Old: t.Owner, New: other.Owner})
	}
	if t.Balance != other.Balance {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/balance", Old: t.Balance, New: other.Balance})
	}
	if t.LateFee != other.LateFee {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/late_fee", Old: t.LateFee, New: other.LateFee})
	}
	if t.Status != other.Status {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/status", Old: t.Status, New: other.Status})
	}
	if t.LastSeen != other.LastSeen {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/last_seen", Old: t.LastSeen, New: other.LastSeen})
	}

	return p
}

func (t *Account) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/owner", "/Owner":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Owner, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Owner))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Owner")
		}
		switch c.Op {
		case "==":
			return t.Owner == _sv, nil
		case "!=":
			return t.Owner != _sv, nil
		case ">":
			return t.Owner > _sv, nil
		case "<":
			return t.Owner < _sv, nil
		case ">=":
			return t.Owner >= _sv, nil
		case "<=":
			return t.Owner <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Owner == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Owner == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/balance", "/Balance":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Balance, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Balance))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case float64:
			_cv = float64(v)
		case int:
			_cv = float64(v)
		default:
			return false, fmt.Errorf("condition value type mismatch for field Balance")
		}
		_fv := float64(t.Balance)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []float64:
				for _, v := range vals {
					if t.Balance == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case float64:
						if t.Balance == iv {
							return true, nil
						}
					case int:
						if float64(t.Balance) == float64(iv) {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/late_fee", "/LateFee":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.LateFee, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.LateFee))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case float64:
			_cv = float64(v)
		case int:
			_cv = float64(v)
		default:
			return false, fmt.Errorf("condition value type mismatch for field LateFee")
		}
		_fv := float64(t.LateFee)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []float64:
				for _, v := range vals {
					if t.LateFee == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case float64:
						if t.LateFee == iv {
							return true, nil
						}
					case int:
						if float64(t.LateFee) == float64(iv) {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/status", "/Status":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Status, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Status))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Status")
		}
		switch c.Op {
		case "==":
			return t.Status == _sv, nil
		case "!=":
			return t.Status != _sv, nil
		case ">":
			return t.Status > _sv, nil
		case "<":
			return t.Status < _sv, nil
		case ">=":
			return t.Status >= _sv, nil
		case "<=":
			return t.Status <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Status == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Status == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/last_seen", "/LastSeen":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.LastSeen, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.LastSeen))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field LastSeen")
		}
		switch c.Op {
		case "==":
			return t.LastSeen == _sv, nil
		case "!=":
			return t.LastSeen != _sv, nil
		case ">":
			return t.LastSeen > _sv, nil
		case "<":
			return t.LastSeen < _sv, nil
		case ">=":
			return t.LastSeen >= _sv, nil
		case "<=":
			return t.LastSeen <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.LastSeen == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.LastSeen == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Account) Equal(other *Account) bool {
	if t.Owner != other.Owner {
		return false
	}
	if t.Balance != other.Balance {
		return false
	}
	if t.LateFee != other.LateFee {
		return false
	}
	if t.Status != other.Status {
		return false
	}
	if t.LastSeen != other.LastSeen {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Account) Clone() *Account {
	res := &Account{
		Owner:    t.Owner,
		Balance:  t.Balance,
		LateFee:  t.LateFee,
		Status:   t.Status,
		LastSeen: t.LastSeen,
	}
	return res
}
