// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/brunoga/deep/v5"
	"strings"
)

// ApplyOperation applies a single operation to DocState efficiently.
func (t *DocState) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(DocState); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/title", "/Title":
		if v, ok := op.New.(string); ok {
			t.Title = v
			return true, nil
		}
	case "/content", "/Content":
		if v, ok := op.New.(string); ok {
			t.Content = v
			return true, nil
		}
	case "/metadata", "/Metadata":
		if v, ok := op.New.(map[string]string); ok {
			t.Metadata = v
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/metadata/") {
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *DocState) Diff(other *DocState) v5.Patch[DocState] {
	p := v5.NewPatch[DocState]()
	if t.Title != other.Title {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/title",
			Old:  t.Title,
			New:  other.Title,
		})
	}
	if t.Content != other.Content {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/content",
			Old:  t.Content,
			New:  other.Content,
		})
	}
	if other.Metadata != nil {
		for k, v := range other.Metadata {
			if t.Metadata == nil {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpReplace,
					Path: fmt.Sprintf("/metadata/%v", k),
					New:  v,
				})
				continue
			}
			if oldV, ok := t.Metadata[k]; !ok || v != oldV {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpReplace,
					Path: fmt.Sprintf("/metadata/%v", k),
					Old:  oldV,
					New:  v,
				})
			}
		}
	}
	if t.Metadata != nil {
		for k, v := range t.Metadata {
			if other.Metadata == nil || !contains(other.Metadata, k) {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpRemove,
					Path: fmt.Sprintf("/metadata/%v", k),
					Old:  v,
				})
			}
		}
	}
	return p
}

func (t *DocState) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Path {
	case "/title", "/Title":
		switch c.Op {
		case "==":
			return t.Title == c.Value.(string), nil
		case "!=":
			return t.Title != c.Value.(string), nil
		}
	case "/content", "/Content":
		switch c.Op {
		case "==":
			return t.Content == c.Value.(string), nil
		case "!=":
			return t.Content != c.Value.(string), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *DocState) Equal(other *DocState) bool {
	if t.Title != other.Title {
		return false
	}
	if t.Content != other.Content {
		return false
	}
	if len(t.Metadata) != len(other.Metadata) {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *DocState) Copy() *DocState {
	res := &DocState{
		Title:   t.Title,
		Content: t.Content,
	}
	if t.Metadata != nil {
		res.Metadata = make(map[string]string)
		for k, v := range t.Metadata {
			res.Metadata[k] = v
		}
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
