// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"reflect"
	"regexp"
	"strings"
)

// ApplyOperation applies a single operation to DocState efficiently.
func (t *DocState) ApplyOperation(op deep.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.EvaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.EvaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(DocState); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(deep.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/title", "/Title":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.Title)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Title != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Title)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Title = v
			return true, nil
		}
	case "/content", "/Content":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.Content)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Content != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Content)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Content = v
			return true, nil
		}
	case "/metadata", "/Metadata":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.Metadata)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(map[string]string); !ok || !deep.Equal(t.Metadata, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Metadata)
			}
		}
		if v, ok := op.New.(map[string]string); ok {
			t.Metadata = v
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/metadata/") {
			parts := strings.Split(op.Path[len("/metadata/"):], "/")
			key := parts[0]
			if op.Kind == deep.OpRemove {
				delete(t.Metadata, key)
				return true, nil
			}
			if t.Metadata == nil {
				t.Metadata = make(map[string]string)
			}
			if v, ok := op.New.(string); ok {
				t.Metadata[key] = v
				return true, nil
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *DocState) Diff(other *DocState) deep.Patch[DocState] {
	p := deep.NewPatch[DocState]()
	if t.Title != other.Title {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/title", Old: t.Title, New: other.Title})
	}
	if t.Content != other.Content {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/content", Old: t.Content, New: other.Content})
	}
	if other.Metadata != nil {
		for k, v := range other.Metadata {
			if t.Metadata == nil {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: fmt.Sprintf("/metadata/%v", k), New: v})
				continue
			}
			if oldV, ok := t.Metadata[k]; !ok || v != oldV {
				kind := deep.OpReplace
				if !ok {
					kind = deep.OpAdd
				}
				p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: fmt.Sprintf("/metadata/%v", k), Old: oldV, New: v})
			}
		}
	}
	if t.Metadata != nil {
		for k, v := range t.Metadata {
			if other.Metadata == nil || !contains(other.Metadata, k) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: fmt.Sprintf("/metadata/%v", k), Old: v})
			}
		}
	}

	return p
}

func (t *DocState) EvaluateCondition(c deep.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.EvaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/title", "/Title":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Title, c.Value.(string)), nil
		}
		if c.Op == "log" {
			deep.Logger().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Title)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Title))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Title")
		}
		switch c.Op {
		case "==":
			return t.Title == _sv, nil
		case "!=":
			return t.Title != _sv, nil
		case ">":
			return t.Title > _sv, nil
		case "<":
			return t.Title < _sv, nil
		case ">=":
			return t.Title >= _sv, nil
		case "<=":
			return t.Title <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Title == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Title == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/content", "/Content":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Content, c.Value.(string)), nil
		}
		if c.Op == "log" {
			deep.Logger().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Content)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Content))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Content")
		}
		switch c.Op {
		case "==":
			return t.Content == _sv, nil
		case "!=":
			return t.Content != _sv, nil
		case ">":
			return t.Content > _sv, nil
		case "<":
			return t.Content < _sv, nil
		case ">=":
			return t.Content >= _sv, nil
		case "<=":
			return t.Content <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Content == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Content == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *DocState) Equal(other *DocState) bool {
	if t.Title != other.Title {
		return false
	}
	if t.Content != other.Content {
		return false
	}
	if len(t.Metadata) != len(other.Metadata) {
		return false
	}
	for k, v := range t.Metadata {
		vOther, ok := other.Metadata[k]
		if !ok {
			return false
		}
		if v != vOther {
			return false
		}
	}
	return true
}

// Copy returns a deep copy of t.
func (t *DocState) Copy() *DocState {
	res := &DocState{
		Title:   t.Title,
		Content: t.Content,
	}
	if t.Metadata != nil {
		res.Metadata = make(map[string]string)
		for k, v := range t.Metadata {
			res.Metadata[k] = v
		}
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface ||
			rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
