// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/brunoga/deep/v5"
	"strings"
)

// ApplyOperation applies a single operation to SystemConfig efficiently.
func (t *SystemConfig) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(SystemConfig); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/app", "/AppName":
		if v, ok := op.New.(string); ok {
			t.AppName = v
			return true, nil
		}
	case "/threads", "/MaxThreads":
		if v, ok := op.New.(int); ok {
			t.MaxThreads = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.MaxThreads = int(f)
			return true, nil
		}
	case "/endpoints", "/Endpoints":
		if v, ok := op.New.(map[string]string); ok {
			t.Endpoints = v
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/endpoints/") {
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *SystemConfig) Diff(other *SystemConfig) v5.Patch[SystemConfig] {
	p := v5.NewPatch[SystemConfig]()
	if t.AppName != other.AppName {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/app",
			Old:  t.AppName,
			New:  other.AppName,
		})
	}
	if t.MaxThreads != other.MaxThreads {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/threads",
			Old:  t.MaxThreads,
			New:  other.MaxThreads,
		})
	}
	if other.Endpoints != nil {
		for k, v := range other.Endpoints {
			if t.Endpoints == nil {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpReplace,
					Path: fmt.Sprintf("/endpoints/%v", k),
					New:  v,
				})
				continue
			}
			if oldV, ok := t.Endpoints[k]; !ok || v != oldV {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpReplace,
					Path: fmt.Sprintf("/endpoints/%v", k),
					Old:  oldV,
					New:  v,
				})
			}
		}
	}
	if t.Endpoints != nil {
		for k, v := range t.Endpoints {
			if other.Endpoints == nil || !contains(other.Endpoints, k) {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpRemove,
					Path: fmt.Sprintf("/endpoints/%v", k),
					Old:  v,
				})
			}
		}
	}
	return p
}

func (t *SystemConfig) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Path {
	case "/app", "/AppName":
		switch c.Op {
		case "==":
			return t.AppName == c.Value.(string), nil
		case "!=":
			return t.AppName != c.Value.(string), nil
		}
	case "/threads", "/MaxThreads":
		switch c.Op {
		case "==":
			return t.MaxThreads == c.Value.(int), nil
		case "!=":
			return t.MaxThreads != c.Value.(int), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *SystemConfig) Equal(other *SystemConfig) bool {
	if t.AppName != other.AppName {
		return false
	}
	if t.MaxThreads != other.MaxThreads {
		return false
	}
	if len(t.Endpoints) != len(other.Endpoints) {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *SystemConfig) Copy() *SystemConfig {
	res := &SystemConfig{
		AppName:    t.AppName,
		MaxThreads: t.MaxThreads,
	}
	if t.Endpoints != nil {
		res.Endpoints = make(map[string]string)
		for k, v := range t.Endpoints {
			res.Endpoints[k] = v
		}
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
