// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	core "github.com/brunoga/deep/v5/core"
	_deepengine "github.com/brunoga/deep/v5/internal/engine"
	"log/slog"
	"regexp"
	"strings"
)

// Patch applies p to t using the generated fast path.
func (t *SystemConfig) Patch(p deep.Patch[SystemConfig], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := _deepengine.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *SystemConfig) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil || ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			if !deep.Equal(*t, op.Old.(SystemConfig)) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(SystemConfig); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/app", "/AppName":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.AppName)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.AppName != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.AppName)
			}
		}
		if v, ok := op.New.(string); ok {
			t.AppName = v
			return true, nil
		}
	case "/threads", "/MaxThreads":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.MaxThreads)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			_oldOK := false
			if _oldV, ok := op.Old.(int); ok {
				_oldOK = t.MaxThreads == _oldV
			}
			if !_oldOK {
				if _oldF, ok := op.Old.(float64); ok {
					_oldOK = float64(t.MaxThreads) == _oldF
				}
			}
			if !_oldOK {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.MaxThreads)
			}
		}
		if v, ok := op.New.(int); ok {
			t.MaxThreads = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.MaxThreads = int(f)
			return true, nil
		}
	case "/endpoints", "/Endpoints":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Endpoints)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(map[string]string); !ok || !deep.Equal(t.Endpoints, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Endpoints)
			}
		}
		if v, ok := op.New.(map[string]string); ok {
			t.Endpoints = v
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/endpoints/") {
			parts := strings.Split(op.Path[len("/endpoints/"):], "/")
			key := parts[0]
			if op.Kind == deep.OpRemove {
				delete(t.Endpoints, key)
				return true, nil
			}
			if t.Endpoints == nil {
				t.Endpoints = make(map[string]string)
			}
			if v, ok := op.New.(string); ok {
				t.Endpoints[key] = v
				return true, nil
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *SystemConfig) Diff(other *SystemConfig) deep.Patch[SystemConfig] {
	p := deep.Patch[SystemConfig]{}
	if t.AppName != other.AppName {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/app", Old: t.AppName, New: other.AppName})
	}
	if t.MaxThreads != other.MaxThreads {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/threads", Old: t.MaxThreads, New: other.MaxThreads})
	}
	if other.Endpoints != nil {
		for k, v := range other.Endpoints {
			if t.Endpoints == nil {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: fmt.Sprintf("/endpoints/%v", k), New: v})
				continue
			}
			if oldV, ok := t.Endpoints[k]; !ok || v != oldV {
				kind := deep.OpReplace
				if !ok {
					kind = deep.OpAdd
				}
				p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: fmt.Sprintf("/endpoints/%v", k), Old: oldV, New: v})
			}
		}
	}
	if t.Endpoints != nil {
		for k, v := range t.Endpoints {
			if other.Endpoints == nil || !contains(other.Endpoints, k) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: fmt.Sprintf("/endpoints/%v", k), Old: v})
			}
		}
	}

	return p
}

func (t *SystemConfig) evaluateCondition(c core.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/app", "/AppName":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return core.CheckType(t.AppName, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.AppName))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field AppName")
		}
		switch c.Op {
		case "==":
			return t.AppName == _sv, nil
		case "!=":
			return t.AppName != _sv, nil
		case ">":
			return t.AppName > _sv, nil
		case "<":
			return t.AppName < _sv, nil
		case ">=":
			return t.AppName >= _sv, nil
		case "<=":
			return t.AppName <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.AppName == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.AppName == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/threads", "/MaxThreads":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return core.CheckType(t.MaxThreads, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.MaxThreads))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field MaxThreads")
		}
		_fv := float64(t.MaxThreads)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.MaxThreads == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.MaxThreads == iv {
							return true, nil
						}
					case float64:
						if float64(t.MaxThreads) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *SystemConfig) Equal(other *SystemConfig) bool {
	if t.AppName != other.AppName {
		return false
	}
	if t.MaxThreads != other.MaxThreads {
		return false
	}
	if len(t.Endpoints) != len(other.Endpoints) {
		return false
	}
	for k, v := range t.Endpoints {
		vOther, ok := other.Endpoints[k]
		if !ok {
			return false
		}
		if v != vOther {
			return false
		}
	}
	return true
}

// Clone returns a deep copy of t.
func (t *SystemConfig) Clone() *SystemConfig {
	res := &SystemConfig{
		AppName:    t.AppName,
		MaxThreads: t.MaxThreads,
	}
	if t.Endpoints != nil {
		res.Endpoints = make(map[string]string)
		for k, v := range t.Endpoints {
			res.Endpoints[k] = v
		}
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
