// Code generated by deep-gen. DO NOT EDIT.
package model

import (
	"fmt"
	deep "github.com/brunoga/deep/v6"
	"github.com/brunoga/deep/v6/condition"
	gen "github.com/brunoga/deep/v6/gen"
	"log/slog"
	"net/netip"
	"reflect"
	"regexp"
	"time"
)

// Patch applies p to t using the generated fast path.
func (t *Task) Patch(p deep.Patch[Task], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Task) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Task); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[Task](op.New); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/id", "/ID":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.ID == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.ID, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.ID)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[string](op.New); ok {
				t.ID = v
				return true, nil
			}
		}
	case "/text", "/Text":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Text == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Text, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Text)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[string](op.New); ok {
				t.Text = v
				return true, nil
			}
		}
	case "/owner", "/Owner":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Owner == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Owner, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Owner)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[string](op.New); ok {
				t.Owner = v
				return true, nil
			}
		}
	case "/done", "/Done":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(bool); ok {
				_match = t.Done == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Done, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Done)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[bool](op.New); ok {
				t.Done = v
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Task) Diff(other *Task) deep.Patch[Task] {
	p := deep.Patch[Task]{}
	if t.ID != other.ID {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/id", Old: t.ID, New: other.ID})
	}
	if t.Text != other.Text {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/text", Old: t.Text, New: other.Text})
	}
	if t.Owner != other.Owner {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/owner", Old: t.Owner, New: other.Owner})
	}
	if t.Done != other.Done {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/done", Old: t.Done, New: other.Done})
	}

	return p
}

func (t *Task) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/id", "/ID":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.ID, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.ID))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field ID")
		}
		switch c.Op {
		case "==":
			return t.ID == _sv, nil
		case "!=":
			return t.ID != _sv, nil
		case ">":
			return t.ID > _sv, nil
		case "<":
			return t.ID < _sv, nil
		case ">=":
			return t.ID >= _sv, nil
		case "<=":
			return t.ID <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.ID == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.ID == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/text", "/Text":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Text, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Text))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Text")
		}
		switch c.Op {
		case "==":
			return t.Text == _sv, nil
		case "!=":
			return t.Text != _sv, nil
		case ">":
			return t.Text > _sv, nil
		case "<":
			return t.Text < _sv, nil
		case ">=":
			return t.Text >= _sv, nil
		case "<=":
			return t.Text <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Text == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Text == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/owner", "/Owner":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Owner, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Owner))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Owner")
		}
		switch c.Op {
		case "==":
			return t.Owner == _sv, nil
		case "!=":
			return t.Owner != _sv, nil
		case ">":
			return t.Owner > _sv, nil
		case "<":
			return t.Owner < _sv, nil
		case ">=":
			return t.Owner >= _sv, nil
		case "<=":
			return t.Owner <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Owner == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Owner == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/done", "/Done":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Done, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Done))
		}
		_bv, _ok := c.Value.(bool)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Done")
		}
		switch c.Op {
		case "==":
			return t.Done == _bv, nil
		case "!=":
			return t.Done != _bv, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Task) Equal(other *Task) bool {
	if t.ID != other.ID {
		return false
	}
	if t.Text != other.Text {
		return false
	}
	if t.Owner != other.Owner {
		return false
	}
	if t.Done != other.Done {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Task) Clone() *Task {
	res := &Task{
		ID:    t.ID,
		Text:  t.Text,
		Owner: t.Owner,
		Done:  t.Done,
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *Incident) Patch(p deep.Patch[Incident], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Incident) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Incident); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[Incident](op.New); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/id", "/ID":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.ID == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.ID, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.ID)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[string](op.New); ok {
				t.ID = v
				return true, nil
			}
		}
	case "/title", "/Title":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Title == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Title, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Title)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[string](op.New); ok {
				t.Title = v
				return true, nil
			}
		}
	case "/severity", "/Severity":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(Severity); ok {
				_match = t.Severity == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Severity, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Severity)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[Severity](op.New); ok {
				t.Severity = v
				return true, nil
			}
		}
	case "/status", "/Status":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(Status); ok {
				_match = t.Status == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Status, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Status)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[Status](op.New); ok {
				t.Status = v
				return true, nil
			}
		}
	case "/commander", "/Commander":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Commander == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Commander, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Commander)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[string](op.New); ok {
				t.Commander = v
				return true, nil
			}
		}
	case "/services", "/Services":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]string); ok {
				_match = deep.Equal(t.Services, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Services, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Services)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[[]string](op.New); ok {
				t.Services = v
				return true, nil
			}
		}
	case "/hosts", "/Hosts":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]netip.Addr); ok {
				_match = deep.Equal(t.Hosts, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Hosts, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Hosts)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[[]netip.Addr](op.New); ok {
				t.Hosts = v
				return true, nil
			}
		}
	case "/tasks", "/Tasks":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]Task); ok {
				_match = deep.Equal(t.Tasks, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Tasks, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Tasks)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[[]Task](op.New); ok {
				t.Tasks = v
				return true, nil
			}
		}
	case "/updated", "/Updated":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(time.Time); ok {
				_match = deep.Equal(t.Updated, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Updated, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Updated)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[time.Time](op.New); ok {
				t.Updated = v
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
//
// Incident values can hold two references to the same value, so a pair of
// values is diffed once, at the first path that reaches it. Every later route
// to a changed pair becomes one alias operation — "make this path hold the
// object that path holds" — appended after the rest. That keeps the patch
// linear where listing every route could be exponential, and applying it
// rebuilds the sharing whatever the target looked like before.
func (t *Incident) Diff(other *Incident) deep.Patch[Incident] {
	seen := gen.NewDiffMemo()
	defer seen.Release()
	p := t.diffShared(other, seen, "")
	p.Operations = append(p.Operations, seen.AliasOperations()...)
	return p
}

// diffShared is Diff threaded with the pairs already visited and the absolute
// path at which t sits.
func (t *Incident) diffShared(other *Incident, seen *gen.DiffMemo, at string) deep.Patch[Incident] {
	p := deep.Patch[Incident]{}
	if t == other || !seen.Enter(t, other, at) {
		return p
	}
	if t.ID != other.ID {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/id", Old: t.ID, New: other.ID})
	}
	if t.Title != other.Title {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/title", Old: t.Title, New: other.Title})
	}
	if t.Severity != other.Severity {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/severity", Old: t.Severity, New: other.Severity})
	}
	if t.Status != other.Status {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/status", Old: t.Status, New: other.Status})
	}
	if t.Commander != other.Commander {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/commander", Old: t.Commander, New: other.Commander})
	}
	if len(t.Services) != len(other.Services) || (t.Services == nil) != (other.Services == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/services", Old: t.Services, New: other.Services})
	} else {
		for i := range t.Services {
			if t.Services[i] != other.Services[i] {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + fmt.Sprintf("/services/%d", i), Old: t.Services[i], New: other.Services[i]})
			}
		}
	}
	if len(t.Hosts) != len(other.Hosts) || (t.Hosts == nil) != (other.Hosts == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/hosts", Old: t.Hosts, New: other.Hosts})
	} else {
		for i := range t.Hosts {
			if !deep.Equal(t.Hosts[i], other.Hosts[i]) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + fmt.Sprintf("/hosts/%d", i), Old: t.Hosts[i], New: other.Hosts[i]})
			}
		}
	}
	{
		if (t.Tasks == nil) != (other.Tasks == nil) {
			p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/tasks", Old: t.Tasks, New: other.Tasks})
		} else {
			otherByKey := make(map[any]int)
			for i, v := range other.Tasks {
				otherByKey[v.ID] = i
			}
			for _, v := range t.Tasks {
				if _, ok := otherByKey[v.ID]; !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/tasks/" + deep.EscapePathKey(fmt.Sprintf("%v", v.ID)), Old: v})
				}
			}
			tByKey := make(map[any]int)
			for i, v := range t.Tasks {
				tByKey[v.ID] = i
			}
			for j := range other.Tasks {
				i, ok := tByKey[other.Tasks[j].ID]
				if !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/tasks/" + deep.EscapePathKey(fmt.Sprintf("%v", other.Tasks[j].ID)), New: other.Tasks[j]})
					continue
				}
				prefix := at + "/tasks/" + deep.EscapePathKey(fmt.Sprintf("%v", other.Tasks[j].ID))
				sub := t.Tasks[i].Diff(&other.Tasks[j])
				for _, op := range sub.Operations {
					if op.Path == "" || op.Path == "/" {
						op.Path = prefix
					} else {
						op.Path = prefix + op.Path
					}
					p.Operations = append(p.Operations, op)
				}
			}
		}
	}
	p.Operations = append(p.Operations, gen.DiffOpaque(at+"/updated", t.Updated, other.Updated)...)

	seen.Leave(t, other, len(p.Operations))
	return p
}

func (t *Incident) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/id", "/ID":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.ID, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.ID))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field ID")
		}
		switch c.Op {
		case "==":
			return t.ID == _sv, nil
		case "!=":
			return t.ID != _sv, nil
		case ">":
			return t.ID > _sv, nil
		case "<":
			return t.ID < _sv, nil
		case ">=":
			return t.ID >= _sv, nil
		case "<=":
			return t.ID <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.ID == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.ID == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/title", "/Title":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Title, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Title))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Title")
		}
		switch c.Op {
		case "==":
			return t.Title == _sv, nil
		case "!=":
			return t.Title != _sv, nil
		case ">":
			return t.Title > _sv, nil
		case "<":
			return t.Title < _sv, nil
		case ">=":
			return t.Title >= _sv, nil
		case "<=":
			return t.Title <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Title == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Title == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/severity", "/Severity":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Severity, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Severity))
		}
		switch c.Op {
		case "==":
			return fmt.Sprintf("%v", t.Severity) == fmt.Sprintf("%v", c.Value), nil
		case "!=":
			return fmt.Sprintf("%v", t.Severity) != fmt.Sprintf("%v", c.Value), nil
		}
	case "/status", "/Status":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Status, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Status))
		}
		switch c.Op {
		case "==":
			return fmt.Sprintf("%v", t.Status) == fmt.Sprintf("%v", c.Value), nil
		case "!=":
			return fmt.Sprintf("%v", t.Status) != fmt.Sprintf("%v", c.Value), nil
		}
	case "/commander", "/Commander":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Commander, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Commander))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Commander")
		}
		switch c.Op {
		case "==":
			return t.Commander == _sv, nil
		case "!=":
			return t.Commander != _sv, nil
		case ">":
			return t.Commander > _sv, nil
		case "<":
			return t.Commander < _sv, nil
		case ">=":
			return t.Commander >= _sv, nil
		case "<=":
			return t.Commander <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Commander == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Commander == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/updated", "/Updated":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Updated, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Updated))
		}
		switch c.Op {
		case "==":
			return fmt.Sprintf("%v", t.Updated) == fmt.Sprintf("%v", c.Value), nil
		case "!=":
			return fmt.Sprintf("%v", t.Updated) != fmt.Sprintf("%v", c.Value), nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
//
// Incident values can hold two references to the same value, so a pair of
// values is compared once however many routes lead to it, and a cycle is
// followed only until it repeats.
func (t *Incident) Equal(other *Incident) bool {
	seen := gen.NewVisitSet()
	defer seen.Release()
	return t.equalShared(other, seen)
}

// equalShared is Equal threaded with the set of pairs already under comparison.
func (t *Incident) equalShared(other *Incident, seen *gen.VisitSet) bool {
	if t == other {
		return true
	}
	if t == nil || other == nil {
		return false
	}
	if !seen.Enter(t, other) {
		// This pair has been reached before: settled if that comparison
		// finished, and a cycle if it is still running — either way there is
		// nothing left to compare here.
		return true
	}
	if t.ID != other.ID {
		return false
	}
	if t.Title != other.Title {
		return false
	}
	if t.Severity != other.Severity {
		return false
	}
	if t.Status != other.Status {
		return false
	}
	if t.Commander != other.Commander {
		return false
	}
	if len(t.Services) != len(other.Services) {
		return false
	}
	for i := range t.Services {
		if t.Services[i] != other.Services[i] {
			return false
		}
	}
	if len(t.Hosts) != len(other.Hosts) {
		return false
	}
	for i := range t.Hosts {
		if !deep.Equal(t.Hosts[i], other.Hosts[i]) {
			return false
		}
	}
	if len(t.Tasks) != len(other.Tasks) {
		return false
	}
	for i := range t.Tasks {
		if !t.Tasks[i].Equal(&other.Tasks[i]) {
			return false
		}
	}
	if !deep.Equal(t.Updated, other.Updated) {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
//
// Incident values can hold two references to the same value — through a
// cycle, or through two routes to one pointer — so the copy keeps track of what
// it has already copied: a value reached more than once is copied once, every
// reference to it in the result points at that one copy, and a reference cycle
// is rebuilt rather than followed forever.
func (t *Incident) Clone() *Incident {
	memo := gen.NewCloneMemo()
	defer memo.Release()
	return t.cloneShared(memo)
}

// cloneShared is Clone threaded with the memo of copies already made.
func (t *Incident) cloneShared(memo *gen.CloneMemo) *Incident {
	if t == nil {
		return nil
	}
	if done, ok := memo.Load(t); ok {
		return done.(*Incident)
	}
	res := &Incident{
		ID:        t.ID,
		Title:     t.Title,
		Severity:  t.Severity,
		Status:    t.Status,
		Commander: t.Commander,
		Updated:   t.Updated,
	}
	// Recorded before the fields are copied, so a reference back to t from
	// anywhere below resolves to res instead of starting the copy again.
	memo.Store(t, res)
	if t.Services != nil {
		res.Services = make([]string, len(t.Services))
		copy(res.Services, t.Services)
	}
	if t.Hosts != nil {
		res.Hosts = make([]netip.Addr, len(t.Hosts))
		for i, v := range t.Hosts {
			res.Hosts[i] = gen.CloneShared(v, memo)
		}
	}
	if t.Tasks != nil {
		res.Tasks = make([]Task, len(t.Tasks))
		for i := range t.Tasks {
			res.Tasks[i] = *t.Tasks[i].Clone()
		}
	}
	return res
}
