// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"reflect"
	"regexp"

	v5 "github.com/brunoga/deep/v5"
)

// ApplyOperation applies a single operation to Resource efficiently.
func (t *Resource) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Resource); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/id", "/ID":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.ID)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.ID != op.Old.(string) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.ID)
			}
		}
		if v, ok := op.New.(string); ok {
			t.ID = v
			return true, nil
		}
	case "/data", "/Data":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Data)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.Data != op.Old.(string) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Data)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Data = v
			return true, nil
		}
	case "/value", "/Value":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Value)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.Value != op.Old.(int) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Value)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Value = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Value = int(f)
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Resource) Diff(other *Resource) v5.Patch[Resource] {
	p := v5.NewPatch[Resource]()
	if t.ID != other.ID {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/id",
			Old:  t.ID,
			New:  other.ID,
		})
	}
	if t.Data != other.Data {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/data",
			Old:  t.Data,
			New:  other.Data,
		})
	}
	if t.Value != other.Value {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/value",
			Old:  t.Value,
			New:  other.Value,
		})
	}
	return p
}

func (t *Resource) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.evaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/id", "/ID":
		switch c.Op {
		case "==":
			return t.ID == c.Value.(string), nil
		case "!=":
			return t.ID != c.Value.(string), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.ID)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.ID))
		case "type":
			return checkType(t.ID, c.Value.(string)), nil
		}
	case "/data", "/Data":
		switch c.Op {
		case "==":
			return t.Data == c.Value.(string), nil
		case "!=":
			return t.Data != c.Value.(string), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.Data)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Data))
		case "type":
			return checkType(t.Data, c.Value.(string)), nil
		}
	case "/value", "/Value":
		switch c.Op {
		case "==":
			return t.Value == c.Value.(int), nil
		case "!=":
			return t.Value != c.Value.(int), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.Value)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Value))
		case "type":
			return checkType(t.Value, c.Value.(string)), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Resource) Equal(other *Resource) bool {
	if t.ID != other.ID {
		return false
	}
	if t.Data != other.Data {
		return false
	}
	if t.Value != other.Value {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Resource) Copy() *Resource {
	res := &Resource{
		ID:    t.ID,
		Data:  t.Data,
		Value: t.Value,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface || rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
