// Code generated by deep-gen. DO NOT EDIT.
package multirun

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	"log/slog"
	"reflect"
	"strings"
)

// Patch applies p to t using the generated fast path.
func (t *Beta) Patch(p deep.Patch[Beta], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Beta) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			old, ok := op.Old.(Beta)
			if !ok || !deep.Equal(*t, old) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Beta); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/m", "/M":
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(map[string]string); !ok || !deep.Equal(t.M, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.M)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(map[string]string); ok {
				t.M = v
				return true, nil
			}
		}
	default:
		if strings.HasPrefix(op.Path, "/m/") {
			parts := strings.Split(op.Path[len("/m/"):], "/")
			key := deep.UnescapePathKey(parts[0])
			if len(parts) == 1 && !op.Strict {
				if op.Kind == deep.OpRemove {
					delete(t.M, key)
					return true, nil
				}
				if v, ok := op.New.(string); ok && (op.Kind == deep.OpAdd || op.Kind == deep.OpReplace) {
					if t.M == nil {
						t.M = make(map[string]string)
					}
					t.M[key] = v
					return true, nil
				}
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Beta) Diff(other *Beta) deep.Patch[Beta] {
	p := deep.Patch[Beta]{}
	if other.M != nil {
		for k, v := range other.M {
			if t.M == nil {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/m/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), New: v})
				continue
			}
			if oldV, ok := t.M[k]; !ok || v != oldV {
				kind := deep.OpReplace
				if !ok {
					kind = deep.OpAdd
				}
				p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: "/m/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: oldV, New: v})
			}
		}
	}
	if t.M != nil {
		for k, v := range t.M {
			if _, ok := other.M[k]; !ok {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: "/m/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: v})
			}
		}
	}

	return p
}

func (t *Beta) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Beta) Equal(other *Beta) bool {
	if len(t.M) != len(other.M) {
		return false
	}
	for k, v := range t.M {
		vOther, ok := other.M[k]
		if !ok {
			return false
		}
		if v != vOther {
			return false
		}
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Beta) Clone() *Beta {
	res := &Beta{}
	if t.M != nil {
		res.M = make(map[string]string)
		for k, v := range t.M {
			res.M[k] = v
		}
	}
	return res
}
