// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"reflect"
	"regexp"
)

// ApplyOperation applies a single operation to ProxyConfig efficiently.
func (t *ProxyConfig) ApplyOperation(op deep.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.EvaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.EvaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(ProxyConfig); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(deep.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/host", "/Host":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.Host)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Host != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Host)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Host = v
			return true, nil
		}
	case "/port", "/Port":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.Port)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			_oldOK := false
			if _oldV, ok := op.Old.(int); ok {
				_oldOK = t.Port == _oldV
			}
			if !_oldOK {
				if _oldF, ok := op.Old.(float64); ok {
					_oldOK = float64(t.Port) == _oldF
				}
			}
			if !_oldOK {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Port)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Port = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Port = int(f)
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *ProxyConfig) Diff(other *ProxyConfig) deep.Patch[ProxyConfig] {
	p := deep.NewPatch[ProxyConfig]()
	if t.Host != other.Host {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/host", Old: t.Host, New: other.Host})
	}
	if t.Port != other.Port {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/port", Old: t.Port, New: other.Port})
	}

	return p
}

func (t *ProxyConfig) EvaluateCondition(c deep.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.EvaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/host", "/Host":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Host, c.Value.(string)), nil
		}
		if c.Op == "log" {
			deep.Logger().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Host)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Host))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Host")
		}
		switch c.Op {
		case "==":
			return t.Host == _sv, nil
		case "!=":
			return t.Host != _sv, nil
		case ">":
			return t.Host > _sv, nil
		case "<":
			return t.Host < _sv, nil
		case ">=":
			return t.Host >= _sv, nil
		case "<=":
			return t.Host <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Host == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Host == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/port", "/Port":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Port, c.Value.(string)), nil
		}
		if c.Op == "log" {
			deep.Logger().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Port)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Port))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Port")
		}
		_fv := float64(t.Port)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Port == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Port == iv {
							return true, nil
						}
					case float64:
						if float64(t.Port) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *ProxyConfig) Equal(other *ProxyConfig) bool {
	if t.Host != other.Host {
		return false
	}
	if t.Port != other.Port {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *ProxyConfig) Copy() *ProxyConfig {
	res := &ProxyConfig{
		Host: t.Host,
		Port: t.Port,
	}
	return res
}

// ApplyOperation applies a single operation to SystemMeta efficiently.
func (t *SystemMeta) ApplyOperation(op deep.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.EvaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.EvaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(SystemMeta); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(deep.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/cid", "/ClusterID":
		return true, fmt.Errorf("field %s is read-only", op.Path)
	case "/proxy", "/Settings":
		if op.Kind == deep.OpLog {
			deep.Logger().Info("deep log", "message", op.New, "path", op.Path, "field", t.Settings)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(ProxyConfig); !ok || !deep.Equal(t.Settings, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Settings)
			}
		}
		if v, ok := op.New.(ProxyConfig); ok {
			t.Settings = v
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *SystemMeta) Diff(other *SystemMeta) deep.Patch[SystemMeta] {
	p := deep.NewPatch[SystemMeta]()
	if t.ClusterID != other.ClusterID {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/cid", Old: t.ClusterID, New: other.ClusterID})
	}
	if t.Settings != other.Settings {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/proxy", Old: t.Settings, New: other.Settings})
	}

	return p
}

func (t *SystemMeta) EvaluateCondition(c deep.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.EvaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.EvaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/cid", "/ClusterID":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.ClusterID, c.Value.(string)), nil
		}
		if c.Op == "log" {
			deep.Logger().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.ClusterID)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.ClusterID))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field ClusterID")
		}
		switch c.Op {
		case "==":
			return t.ClusterID == _sv, nil
		case "!=":
			return t.ClusterID != _sv, nil
		case ">":
			return t.ClusterID > _sv, nil
		case "<":
			return t.ClusterID < _sv, nil
		case ">=":
			return t.ClusterID >= _sv, nil
		case "<=":
			return t.ClusterID <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.ClusterID == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.ClusterID == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *SystemMeta) Equal(other *SystemMeta) bool {
	if t.ClusterID != other.ClusterID {
		return false
	}
	if !(&t.Settings).Equal((&other.Settings)) {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *SystemMeta) Copy() *SystemMeta {
	res := &SystemMeta{
		ClusterID: t.ClusterID,
	}
	res.Settings = *(&t.Settings).Copy()
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface ||
			rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
