// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	_deepengine "github.com/brunoga/deep/v5/internal/engine"
	"log/slog"
	"regexp"
)

// Patch applies p to t using the generated fast path.
func (t *ProxyConfig) Patch(p deep.Patch[ProxyConfig], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := _deepengine.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *ProxyConfig) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil || ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			if !deep.Equal(*t, op.Old.(ProxyConfig)) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(ProxyConfig); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/host", "/Host":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Host)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Host != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Host)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Host = v
			return true, nil
		}
	case "/port", "/Port":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Port)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			_oldOK := false
			if _oldV, ok := op.Old.(int); ok {
				_oldOK = t.Port == _oldV
			}
			if !_oldOK {
				if _oldF, ok := op.Old.(float64); ok {
					_oldOK = float64(t.Port) == _oldF
				}
			}
			if !_oldOK {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Port)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Port = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Port = int(f)
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *ProxyConfig) Diff(other *ProxyConfig) deep.Patch[ProxyConfig] {
	p := deep.Patch[ProxyConfig]{}
	if t.Host != other.Host {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/host", Old: t.Host, New: other.Host})
	}
	if t.Port != other.Port {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/port", Old: t.Port, New: other.Port})
	}

	return p
}

func (t *ProxyConfig) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/host", "/Host":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return condition.CheckType(t.Host, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Host))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Host")
		}
		switch c.Op {
		case "==":
			return t.Host == _sv, nil
		case "!=":
			return t.Host != _sv, nil
		case ">":
			return t.Host > _sv, nil
		case "<":
			return t.Host < _sv, nil
		case ">=":
			return t.Host >= _sv, nil
		case "<=":
			return t.Host <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Host == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Host == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/port", "/Port":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return condition.CheckType(t.Port, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Port))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Port")
		}
		_fv := float64(t.Port)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Port == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Port == iv {
							return true, nil
						}
					case float64:
						if float64(t.Port) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *ProxyConfig) Equal(other *ProxyConfig) bool {
	if t.Host != other.Host {
		return false
	}
	if t.Port != other.Port {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *ProxyConfig) Clone() *ProxyConfig {
	res := &ProxyConfig{
		Host: t.Host,
		Port: t.Port,
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *SystemMeta) Patch(p deep.Patch[SystemMeta], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := _deepengine.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *SystemMeta) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil || ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			if !deep.Equal(*t, op.Old.(SystemMeta)) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(SystemMeta); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/cid", "/ClusterID":
		return true, fmt.Errorf("field %s is read-only", op.Path)
	case "/proxy", "/Settings":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Settings)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(ProxyConfig); !ok || !deep.Equal(t.Settings, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Settings)
			}
		}
		if v, ok := op.New.(ProxyConfig); ok {
			t.Settings = v
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *SystemMeta) Diff(other *SystemMeta) deep.Patch[SystemMeta] {
	p := deep.Patch[SystemMeta]{}
	if t.ClusterID != other.ClusterID {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/cid", Old: t.ClusterID, New: other.ClusterID})
	}
	if t.Settings != other.Settings {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/proxy", Old: t.Settings, New: other.Settings})
	}

	return p
}

func (t *SystemMeta) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/cid", "/ClusterID":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return condition.CheckType(t.ClusterID, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.ClusterID))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field ClusterID")
		}
		switch c.Op {
		case "==":
			return t.ClusterID == _sv, nil
		case "!=":
			return t.ClusterID != _sv, nil
		case ">":
			return t.ClusterID > _sv, nil
		case "<":
			return t.ClusterID < _sv, nil
		case ">=":
			return t.ClusterID >= _sv, nil
		case "<=":
			return t.ClusterID <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.ClusterID == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.ClusterID == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *SystemMeta) Equal(other *SystemMeta) bool {
	if t.ClusterID != other.ClusterID {
		return false
	}
	if !(&t.Settings).Equal((&other.Settings)) {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *SystemMeta) Clone() *SystemMeta {
	res := &SystemMeta{
		ClusterID: t.ClusterID,
	}
	res.Settings = *(&t.Settings).Clone()
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
