// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/brunoga/deep/v5"
)

// ApplyOperation applies a single operation to StrictUser efficiently.
func (t *StrictUser) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(StrictUser); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/name", "/Name":
		if v, ok := op.New.(string); ok {
			t.Name = v
			return true, nil
		}
	case "/age", "/Age":
		if v, ok := op.New.(int); ok {
			t.Age = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Age = int(f)
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *StrictUser) Diff(other *StrictUser) v5.Patch[StrictUser] {
	p := v5.NewPatch[StrictUser]()
	if t.Name != other.Name {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/name",
			Old:  t.Name,
			New:  other.Name,
		})
	}
	if t.Age != other.Age {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/age",
			Old:  t.Age,
			New:  other.Age,
		})
	}
	return p
}

func (t *StrictUser) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Path {
	case "/name", "/Name":
		switch c.Op {
		case "==":
			return t.Name == c.Value.(string), nil
		case "!=":
			return t.Name != c.Value.(string), nil
		}
	case "/age", "/Age":
		switch c.Op {
		case "==":
			return t.Age == c.Value.(int), nil
		case "!=":
			return t.Age != c.Value.(int), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *StrictUser) Equal(other *StrictUser) bool {
	if t.Name != other.Name {
		return false
	}
	if t.Age != other.Age {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *StrictUser) Copy() *StrictUser {
	res := &StrictUser{
		Name: t.Name,
		Age:  t.Age,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
