// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	core "github.com/brunoga/deep/v5/core"
	"log/slog"
)

// Patch applies p to t using the generated fast path.
func (t *Fleet) Patch(p deep.Patch[Fleet], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Fleet) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil || ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			if !deep.Equal(*t, op.Old.(Fleet)) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Fleet); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/devices", "/Devices":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Devices)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(map[DeviceID]string); !ok || !deep.Equal(t.Devices, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Devices)
			}
		}
		if v, ok := op.New.(map[DeviceID]string); ok {
			t.Devices = v
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Fleet) Diff(other *Fleet) deep.Patch[Fleet] {
	p := deep.Patch[Fleet]{}
	if other.Devices != nil {
		for k, v := range other.Devices {
			if t.Devices == nil {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: fmt.Sprintf("/devices/%v", k), New: v})
				continue
			}
			if oldV, ok := t.Devices[k]; !ok || v != oldV {
				kind := deep.OpReplace
				if !ok {
					kind = deep.OpAdd
				}
				p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: fmt.Sprintf("/devices/%v", k), Old: oldV, New: v})
			}
		}
	}
	if t.Devices != nil {
		for k, v := range t.Devices {
			if other.Devices == nil || !contains(other.Devices, k) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: fmt.Sprintf("/devices/%v", k), Old: v})
			}
		}
	}

	return p
}

func (t *Fleet) evaluateCondition(c core.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Fleet) Equal(other *Fleet) bool {
	if len(t.Devices) != len(other.Devices) {
		return false
	}
	for k, v := range t.Devices {
		vOther, ok := other.Devices[k]
		if !ok {
			return false
		}
		if v != vOther {
			return false
		}
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Fleet) Clone() *Fleet {
	res := &Fleet{}
	if t.Devices != nil {
		res.Devices = make(map[DeviceID]string)
		for k, v := range t.Devices {
			res.Devices[k] = v
		}
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
