// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	"log/slog"
	"reflect"
	"regexp"
	"strings"
)

// Patch applies p to t using the generated fast path.
func (t *Meta) Patch(p deep.Patch[Meta], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Meta) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			old, ok := op.Old.(Meta)
			if !ok || !deep.Equal(*t, old) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Meta); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/region", "/Region":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Region == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Region, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Region)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Region = v
				return true, nil
			}
		}
	case "/zone", "/Zone":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Zone == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Zone, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Zone)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Zone = v
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Meta) Diff(other *Meta) deep.Patch[Meta] {
	p := deep.Patch[Meta]{}
	if t.Region != other.Region {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/region", Old: t.Region, New: other.Region})
	}
	if t.Zone != other.Zone {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/zone", Old: t.Zone, New: other.Zone})
	}

	return p
}

func (t *Meta) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/region", "/Region":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Region, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Region))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Region")
		}
		switch c.Op {
		case "==":
			return t.Region == _sv, nil
		case "!=":
			return t.Region != _sv, nil
		case ">":
			return t.Region > _sv, nil
		case "<":
			return t.Region < _sv, nil
		case ">=":
			return t.Region >= _sv, nil
		case "<=":
			return t.Region <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Region == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Region == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/zone", "/Zone":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Zone, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Zone))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Zone")
		}
		switch c.Op {
		case "==":
			return t.Zone == _sv, nil
		case "!=":
			return t.Zone != _sv, nil
		case ">":
			return t.Zone > _sv, nil
		case "<":
			return t.Zone < _sv, nil
		case ">=":
			return t.Zone >= _sv, nil
		case "<=":
			return t.Zone <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Zone == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Zone == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Meta) Equal(other *Meta) bool {
	if t.Region != other.Region {
		return false
	}
	if t.Zone != other.Zone {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Meta) Clone() *Meta {
	res := &Meta{
		Region: t.Region,
		Zone:   t.Zone,
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *Limits) Patch(p deep.Patch[Limits], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Limits) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			old, ok := op.Old.(Limits)
			if !ok || !deep.Equal(*t, old) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Limits); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/cpu", "/CPU":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.CPU == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.CPU, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.CPU)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.CPU = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.CPU = int(f)
				return true, nil
			}
		}
	case "/memory", "/Memory":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Memory == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Memory, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Memory)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Memory = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Memory = int(f)
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Limits) Diff(other *Limits) deep.Patch[Limits] {
	p := deep.Patch[Limits]{}
	if t.CPU != other.CPU {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/cpu", Old: t.CPU, New: other.CPU})
	}
	if t.Memory != other.Memory {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/memory", Old: t.Memory, New: other.Memory})
	}

	return p
}

func (t *Limits) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/cpu", "/CPU":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.CPU, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.CPU))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field CPU")
		}
		_fv := float64(t.CPU)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.CPU == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.CPU == iv {
							return true, nil
						}
					case float64:
						if float64(t.CPU) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/memory", "/Memory":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Memory, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Memory))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Memory")
		}
		_fv := float64(t.Memory)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Memory == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Memory == iv {
							return true, nil
						}
					case float64:
						if float64(t.Memory) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Limits) Equal(other *Limits) bool {
	if t.CPU != other.CPU {
		return false
	}
	if t.Memory != other.Memory {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Limits) Clone() *Limits {
	res := &Limits{
		CPU:    t.CPU,
		Memory: t.Memory,
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *Server) Patch(p deep.Patch[Server], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Server) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			old, ok := op.Old.(Server)
			if !ok || !deep.Equal(*t, old) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Server); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/Meta":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(Meta); ok {
				_match = deep.Equal(t.Meta, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Meta, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Meta)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(Meta); ok {
				t.Meta = v
				return true, nil
			}
		}
	case "/name", "/Name":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Name == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Name, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Name = v
				return true, nil
			}
		}
	case "/limits", "/Limits":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(Limits); ok {
				_match = deep.Equal(t.Limits, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Limits, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Limits)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(Limits); ok {
				t.Limits = v
				return true, nil
			}
		}
	case "/sidecar", "/Sidecar":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(*Limits); ok {
				_match = deep.Equal(t.Sidecar, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Sidecar, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Sidecar)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(*Limits); ok {
				t.Sidecar = v
				return true, nil
			}
		}
	default:
		if strings.HasPrefix(op.Path, "/Meta/") {
			op.Path = op.Path[len("/Meta/")-1:]
			return (&t.Meta).applyOperation(op, logger)
		}
		if strings.HasPrefix(op.Path, "/limits/") {
			op.Path = op.Path[len("/limits/")-1:]
			return (&t.Limits).applyOperation(op, logger)
		}
		if strings.HasPrefix(op.Path, "/sidecar/") {
			if t.Sidecar != nil {
				op.Path = op.Path[len("/sidecar/")-1:]
				return t.Sidecar.applyOperation(op, logger)
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Server) Diff(other *Server) deep.Patch[Server] {
	p := deep.Patch[Server]{}
	subMeta := (&t.Meta).Diff(&other.Meta)
	for _, op := range subMeta.Operations {
		if op.Path == "" || op.Path == "/" {
			op.Path = "/Meta"
		} else {
			op.Path = "/Meta" + op.Path
		}
		p.Operations = append(p.Operations, op)
	}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/name", Old: t.Name, New: other.Name})
	}
	subLimits := (&t.Limits).Diff(&other.Limits)
	for _, op := range subLimits.Operations {
		if op.Path == "" || op.Path == "/" {
			op.Path = "/limits"
		} else {
			op.Path = "/limits" + op.Path
		}
		p.Operations = append(p.Operations, op)
	}
	if t.Sidecar == nil && other.Sidecar != nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: "/sidecar", New: other.Sidecar})
	} else if t.Sidecar != nil && other.Sidecar == nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: "/sidecar", Old: t.Sidecar})
	} else if t.Sidecar != nil && other.Sidecar != nil {
		subSidecar := t.Sidecar.Diff(other.Sidecar)
		for _, op := range subSidecar.Operations {
			if op.Path == "" || op.Path == "/" {
				op.Path = "/sidecar"
			} else {
				op.Path = "/sidecar" + op.Path
			}
			p.Operations = append(p.Operations, op)
		}
	}

	return p
}

func (t *Server) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/name", "/Name":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Name, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Name))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Name")
		}
		switch c.Op {
		case "==":
			return t.Name == _sv, nil
		case "!=":
			return t.Name != _sv, nil
		case ">":
			return t.Name > _sv, nil
		case "<":
			return t.Name < _sv, nil
		case ">=":
			return t.Name >= _sv, nil
		case "<=":
			return t.Name <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Name == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Name == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Server) Equal(other *Server) bool {
	if !(&t.Meta).Equal((&other.Meta)) {
		return false
	}
	if t.Name != other.Name {
		return false
	}
	if !(&t.Limits).Equal((&other.Limits)) {
		return false
	}
	if (t.Sidecar == nil) != (other.Sidecar == nil) {
		return false
	}
	if t.Sidecar != nil && !t.Sidecar.Equal(other.Sidecar) {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Server) Clone() *Server {
	res := &Server{
		Name: t.Name,
	}
	res.Meta = *(&t.Meta).Clone()
	res.Limits = *(&t.Limits).Clone()
	if t.Sidecar != nil {
		res.Sidecar = t.Sidecar.Clone()
	}
	return res
}
