// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	core "github.com/brunoga/deep/v5/core"
	_deepengine "github.com/brunoga/deep/v5/internal/engine"
	"log/slog"
	"regexp"
	"strings"
)

// Patch applies p to t using the generated fast path.
func (t *User) Patch(p deep.Patch[User], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := _deepengine.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *User) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil || ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			if !deep.Equal(*t, op.Old.(User)) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(User); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/name", "/Name":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Name)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Name != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Name = v
			return true, nil
		}
	case "/email", "/Email":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Email)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Email != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Email)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Email = v
			return true, nil
		}
	case "/tags", "/Tags":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Tags)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if old, ok := op.Old.(map[string]bool); !ok || !deep.Equal(t.Tags, old) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Tags)
			}
		}
		if v, ok := op.New.(map[string]bool); ok {
			t.Tags = v
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/tags/") {
			parts := strings.Split(op.Path[len("/tags/"):], "/")
			key := parts[0]
			if op.Kind == deep.OpRemove {
				delete(t.Tags, key)
				return true, nil
			}
			if t.Tags == nil {
				t.Tags = make(map[string]bool)
			}
			if v, ok := op.New.(bool); ok {
				t.Tags[key] = v
				return true, nil
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *User) Diff(other *User) deep.Patch[User] {
	p := deep.Patch[User]{}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/name", Old: t.Name, New: other.Name})
	}
	if t.Email != other.Email {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/email", Old: t.Email, New: other.Email})
	}
	if other.Tags != nil {
		for k, v := range other.Tags {
			if t.Tags == nil {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: fmt.Sprintf("/tags/%v", k), New: v})
				continue
			}
			if oldV, ok := t.Tags[k]; !ok || v != oldV {
				kind := deep.OpReplace
				if !ok {
					kind = deep.OpAdd
				}
				p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: fmt.Sprintf("/tags/%v", k), Old: oldV, New: v})
			}
		}
	}
	if t.Tags != nil {
		for k, v := range t.Tags {
			if other.Tags == nil || !contains(other.Tags, k) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: fmt.Sprintf("/tags/%v", k), Old: v})
			}
		}
	}

	return p
}

func (t *User) evaluateCondition(c core.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/name", "/Name":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return core.CheckType(t.Name, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Name))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Name")
		}
		switch c.Op {
		case "==":
			return t.Name == _sv, nil
		case "!=":
			return t.Name != _sv, nil
		case ">":
			return t.Name > _sv, nil
		case "<":
			return t.Name < _sv, nil
		case ">=":
			return t.Name >= _sv, nil
		case "<=":
			return t.Name <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Name == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Name == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/email", "/Email":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return core.CheckType(t.Email, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Email))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Email")
		}
		switch c.Op {
		case "==":
			return t.Email == _sv, nil
		case "!=":
			return t.Email != _sv, nil
		case ">":
			return t.Email > _sv, nil
		case "<":
			return t.Email < _sv, nil
		case ">=":
			return t.Email >= _sv, nil
		case "<=":
			return t.Email <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Email == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Email == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *User) Equal(other *User) bool {
	if t.Name != other.Name {
		return false
	}
	if t.Email != other.Email {
		return false
	}
	if len(t.Tags) != len(other.Tags) {
		return false
	}
	for k, v := range t.Tags {
		vOther, ok := other.Tags[k]
		if !ok {
			return false
		}
		if v != vOther {
			return false
		}
	}
	return true
}

// Clone returns a deep copy of t.
func (t *User) Clone() *User {
	res := &User{
		Name:  t.Name,
		Email: t.Email,
	}
	if t.Tags != nil {
		res.Tags = make(map[string]bool)
		for k, v := range t.Tags {
			res.Tags[k] = v
		}
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
