// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"reflect"
	"regexp"
	"strings"

	v5 "github.com/brunoga/deep/v5"
)

// ApplyOperation applies a single operation to GameWorld efficiently.
func (t *GameWorld) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(GameWorld); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/players", "/Players":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Players)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			// Complex strict check skipped in prototype
		}
		if v, ok := op.New.(map[string]*Player); ok {
			t.Players = v
			return true, nil
		}
	case "/time", "/Time":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Time)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.Time != op.Old.(int) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Time)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Time = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Time = int(f)
			return true, nil
		}
	default:
		if strings.HasPrefix(op.Path, "/players/") {
			parts := strings.Split(op.Path[len("/players/"):], "/")
			key := parts[0]
			if val, ok := t.Players[key]; ok && val != nil {
				op.Path = "/"
				if len(parts) > 1 {
					op.Path = "/" + strings.Join(parts[1:], "/")
				}
				return val.ApplyOperation(op)
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *GameWorld) Diff(other *GameWorld) v5.Patch[GameWorld] {
	p := v5.NewPatch[GameWorld]()
	if other.Players != nil {
		for k, v := range other.Players {
			if t.Players == nil {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpReplace,
					Path: fmt.Sprintf("/players/%v", k),
					New:  v,
				})
				continue
			}
			if oldV, ok := t.Players[k]; !ok || !oldV.Equal(v) {
				kind := v5.OpReplace
				if !ok {
					kind = v5.OpAdd
				}
				p.Operations = append(p.Operations, v5.Operation{
					Kind: kind,
					Path: fmt.Sprintf("/players/%v", k),
					Old:  oldV,
					New:  v,
				})
			}
		}
	}
	if t.Players != nil {
		for k, v := range t.Players {
			if other.Players == nil || !contains(other.Players, k) {
				p.Operations = append(p.Operations, v5.Operation{
					Kind: v5.OpRemove,
					Path: fmt.Sprintf("/players/%v", k),
					Old:  v,
				})
			}
		}
	}
	if t.Time != other.Time {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/time",
			Old:  t.Time,
			New:  other.Time,
		})
	}
	return p
}

func (t *GameWorld) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.evaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/time", "/Time":
		switch c.Op {
		case "==":
			return t.Time == c.Value.(int), nil
		case "!=":
			return t.Time != c.Value.(int), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.Time)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Time))
		case "type":
			return checkType(t.Time, c.Value.(string)), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *GameWorld) Equal(other *GameWorld) bool {
	if len(t.Players) != len(other.Players) {
		return false
	}
	if t.Time != other.Time {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *GameWorld) Copy() *GameWorld {
	res := &GameWorld{
		Time: t.Time,
	}
	if t.Players != nil {
		res.Players = make(map[string]*Player)
		for k, v := range t.Players {
			if v != nil {
				res.Players[k] = v.Copy()
			}
		}
	}
	return res
}

// ApplyOperation applies a single operation to Player efficiently.
func (t *Player) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Player); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/x", "/X":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.X)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.X != op.Old.(int) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.X)
			}
		}
		if v, ok := op.New.(int); ok {
			t.X = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.X = int(f)
			return true, nil
		}
	case "/y", "/Y":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Y)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.Y != op.Old.(int) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Y)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Y = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Y = int(f)
			return true, nil
		}
	case "/name", "/Name":
		if op.Kind == v5.OpLog {
			fmt.Printf("DEEP LOG: %v (at %s, field value: %v)\n", op.New, op.Path, t.Name)
			return true, nil
		}
		if op.Kind == v5.OpReplace && op.Strict {
			if t.Name != op.Old.(string) {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Name = v
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Player) Diff(other *Player) v5.Patch[Player] {
	p := v5.NewPatch[Player]()
	if t.X != other.X {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/x",
			Old:  t.X,
			New:  other.X,
		})
	}
	if t.Y != other.Y {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/y",
			Old:  t.Y,
			New:  other.Y,
		})
	}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/name",
			Old:  t.Name,
			New:  other.Name,
		})
	}
	return p
}

func (t *Player) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Apply {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Apply) > 0 {
			ok, err := t.evaluateCondition(*c.Apply[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/x", "/X":
		switch c.Op {
		case "==":
			return t.X == c.Value.(int), nil
		case "!=":
			return t.X != c.Value.(int), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.X)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.X))
		case "type":
			return checkType(t.X, c.Value.(string)), nil
		}
	case "/y", "/Y":
		switch c.Op {
		case "==":
			return t.Y == c.Value.(int), nil
		case "!=":
			return t.Y != c.Value.(int), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.Y)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Y))
		case "type":
			return checkType(t.Y, c.Value.(string)), nil
		}
	case "/name", "/Name":
		switch c.Op {
		case "==":
			return t.Name == c.Value.(string), nil
		case "!=":
			return t.Name != c.Value.(string), nil
		case "log":
			fmt.Printf("DEEP LOG CONDITION: %v (at %s, value: %v)\n", c.Value, c.Path, t.Name)
			return true, nil
		case "matches":
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Name))
		case "type":
			return checkType(t.Name, c.Value.(string)), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Player) Equal(other *Player) bool {
	if t.X != other.X {
		return false
	}
	if t.Y != other.Y {
		return false
	}
	if t.Name != other.Name {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Player) Copy() *Player {
	res := &Player{
		X:    t.X,
		Y:    t.Y,
		Name: t.Name,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface || rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
