// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v6"
	"github.com/brunoga/deep/v6/condition"
	gen "github.com/brunoga/deep/v6/gen"
	"log/slog"
	"reflect"
	"regexp"
)

// Patch applies p to t using the generated fast path.
func (t *Playlist) Patch(p deep.Patch[Playlist], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Playlist) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Playlist); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[Playlist](op.New); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/name", "/Name":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Name == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Name, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[string](op.New); ok {
				t.Name = v
				return true, nil
			}
		}
	case "/tracks", "/Tracks":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]string); ok {
				_match = deep.Equal(t.Tracks, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Tracks, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Tracks)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := deep.ValueAs[[]string](op.New); ok {
				t.Tracks = v
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Playlist) Diff(other *Playlist) deep.Patch[Playlist] {
	p := deep.Patch[Playlist]{}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/name", Old: t.Name, New: other.Name})
	}
	if len(t.Tracks) != len(other.Tracks) || (t.Tracks == nil) != (other.Tracks == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/tracks", Old: t.Tracks, New: other.Tracks})
	} else {
		for i := range t.Tracks {
			if t.Tracks[i] != other.Tracks[i] {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: fmt.Sprintf("/tracks/%d", i), Old: t.Tracks[i], New: other.Tracks[i]})
			}
		}
	}

	return p
}

func (t *Playlist) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/name", "/Name":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Name, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Name))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Name")
		}
		switch c.Op {
		case "==":
			return t.Name == _sv, nil
		case "!=":
			return t.Name != _sv, nil
		case ">":
			return t.Name > _sv, nil
		case "<":
			return t.Name < _sv, nil
		case ">=":
			return t.Name >= _sv, nil
		case "<=":
			return t.Name <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Name == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Name == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Playlist) Equal(other *Playlist) bool {
	if t.Name != other.Name {
		return false
	}
	if len(t.Tracks) != len(other.Tracks) {
		return false
	}
	for i := range t.Tracks {
		if t.Tracks[i] != other.Tracks[i] {
			return false
		}
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Playlist) Clone() *Playlist {
	res := &Playlist{
		Name: t.Name,
	}
	if t.Tracks != nil {
		res.Tracks = make([]string, len(t.Tracks))
		copy(res.Tracks, t.Tracks)
	}
	return res
}
