// Code generated by deep-gen. DO NOT EDIT.
package graph

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	"log/slog"
	"reflect"
	"regexp"
	"strings"
)

// Patch applies p to t using the generated fast path.
func (t *Label) Patch(p deep.Patch[Label], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Label) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Label); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Label); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/text", "/Text":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Text == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Text, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Text)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Text = v
				return true, nil
			}
		}
	case "/rank", "/Rank":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Rank == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Rank, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Rank)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Rank = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Rank = int(f)
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Label) Diff(other *Label) deep.Patch[Label] {
	p := deep.Patch[Label]{}
	if t.Text != other.Text {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/text", Old: t.Text, New: other.Text})
	}
	if t.Rank != other.Rank {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/rank", Old: t.Rank, New: other.Rank})
	}

	return p
}

func (t *Label) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/text", "/Text":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Text, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Text))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Text")
		}
		switch c.Op {
		case "==":
			return t.Text == _sv, nil
		case "!=":
			return t.Text != _sv, nil
		case ">":
			return t.Text > _sv, nil
		case "<":
			return t.Text < _sv, nil
		case ">=":
			return t.Text >= _sv, nil
		case "<=":
			return t.Text <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Text == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Text == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/rank", "/Rank":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Rank, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Rank))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Rank")
		}
		_fv := float64(t.Rank)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Rank == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Rank == iv {
							return true, nil
						}
					case float64:
						if float64(t.Rank) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Label) Equal(other *Label) bool {
	if t.Text != other.Text {
		return false
	}
	if t.Rank != other.Rank {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Label) Clone() *Label {
	res := &Label{
		Text: t.Text,
		Rank: t.Rank,
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *Edge) Patch(p deep.Patch[Edge], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Edge) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Edge); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Edge); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/weight", "/Weight":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Weight == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Weight, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Weight)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Weight = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Weight = int(f)
				return true, nil
			}
		}
	case "/to", "/To":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(*Node); ok {
				_match = deep.Equal(t.To, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.To, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.To)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(*Node); ok {
				t.To = v
				return true, nil
			}
		}
	default:
		if strings.HasPrefix(op.Path, "/to/") {
			if t.To != nil {
				op.Path = op.Path[len("/to/")-1:]
				return t.To.applyOperation(op, logger)
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
//
// Edge values can hold two references to the same value, so a pair of
// values is diffed once, at the first path that reaches it. Every later route
// to a changed pair becomes one alias operation — "make this path hold the
// object that path holds" — appended after the rest. That keeps the patch
// linear where listing every route could be exponential, and applying it
// rebuilds the sharing whatever the target looked like before.
func (t *Edge) Diff(other *Edge) deep.Patch[Edge] {
	seen := deep.NewDiffMemo()
	defer seen.Release()
	p := t.diffShared(other, seen, "")
	p.Operations = append(p.Operations, seen.AliasOperations()...)
	return p
}

// diffShared is Diff threaded with the pairs already visited and the absolute
// path at which t sits.
func (t *Edge) diffShared(other *Edge, seen *deep.DiffMemo, at string) deep.Patch[Edge] {
	p := deep.Patch[Edge]{}
	if t == other || !seen.Enter(t, other, at) {
		return p
	}
	if t.Weight != other.Weight {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/weight", Old: t.Weight, New: other.Weight})
	}
	if t.To == nil && other.To != nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/to", New: other.To})
	} else if t.To != nil && other.To == nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/to", Old: t.To})
	} else if t.To != nil && other.To != nil {
		subTo := t.To.diffShared(other.To, seen, at+"/to")
		p.Operations = append(p.Operations, subTo.Operations...)
	}

	seen.Leave(t, other, len(p.Operations))
	return p
}

func (t *Edge) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/weight", "/Weight":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Weight, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Weight))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Weight")
		}
		_fv := float64(t.Weight)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Weight == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Weight == iv {
							return true, nil
						}
					case float64:
						if float64(t.Weight) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
//
// Edge values can hold two references to the same value, so a pair of
// values is compared once however many routes lead to it, and a cycle is
// followed only until it repeats.
func (t *Edge) Equal(other *Edge) bool {
	seen := deep.NewVisitSet()
	defer seen.Release()
	return t.equalShared(other, seen)
}

// equalShared is Equal threaded with the set of pairs already under comparison.
func (t *Edge) equalShared(other *Edge, seen *deep.VisitSet) bool {
	if t == other {
		return true
	}
	if t == nil || other == nil {
		return false
	}
	if !seen.Enter(t, other) {
		// This pair has been reached before: settled if that comparison
		// finished, and a cycle if it is still running — either way there is
		// nothing left to compare here.
		return true
	}
	if t.Weight != other.Weight {
		return false
	}
	if (t.To == nil) != (other.To == nil) {
		return false
	}
	if t.To != nil && !t.To.equalShared(other.To, seen) {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
//
// Edge values can hold two references to the same value — through a
// cycle, or through two routes to one pointer — so the copy keeps track of what
// it has already copied: a value reached more than once is copied once, every
// reference to it in the result points at that one copy, and a reference cycle
// is rebuilt rather than followed forever.
func (t *Edge) Clone() *Edge {
	memo := deep.NewCloneMemo()
	defer memo.Release()
	return t.cloneShared(memo)
}

// cloneShared is Clone threaded with the memo of copies already made.
func (t *Edge) cloneShared(memo *deep.CloneMemo) *Edge {
	if t == nil {
		return nil
	}
	if done, ok := memo.Load(t); ok {
		return done.(*Edge)
	}
	res := &Edge{
		Weight: t.Weight,
	}
	// Recorded before the fields are copied, so a reference back to t from
	// anywhere below resolves to res instead of starting the copy again.
	memo.Store(t, res)
	if t.To != nil {
		res.To = t.To.cloneShared(memo)
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *Node) Patch(p deep.Patch[Node], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Node) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Node); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Node); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/name", "/Name":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Name == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Name, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Name = v
				return true, nil
			}
		}
	case "/label", "/Label":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(Label); ok {
				_match = deep.Equal(t.Label, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Label, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Label)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(Label); ok {
				t.Label = v
				return true, nil
			}
		}
	case "/next", "/Next":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(*Node); ok {
				_match = deep.Equal(t.Next, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Next, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Next)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(*Node); ok {
				t.Next = v
				return true, nil
			}
		}
	case "/peers", "/Peers":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]*Node); ok {
				_match = deep.Equal(t.Peers, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Peers, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Peers)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.([]*Node); ok {
				t.Peers = v
				return true, nil
			}
		}
	case "/children", "/Children":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(map[string]*Node); ok {
				_match = deep.Equal(t.Children, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Children, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Children)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(map[string]*Node); ok {
				t.Children = v
				return true, nil
			}
		}
	case "/edges", "/Edges":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]Edge); ok {
				_match = deep.Equal(t.Edges, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Edges, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Edges)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.([]Edge); ok {
				t.Edges = v
				return true, nil
			}
		}
	case "/links", "/Links":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(map[string]Edge); ok {
				_match = deep.Equal(t.Links, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Links, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Links)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(map[string]Edge); ok {
				t.Links = v
				return true, nil
			}
		}
	case "/tags", "/Tags":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(map[string]string); ok {
				_match = deep.Equal(t.Tags, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Tags, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Tags)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(map[string]string); ok {
				t.Tags = v
				return true, nil
			}
		}
	case "/scores", "/Scores":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]int); ok {
				_match = deep.Equal(t.Scores, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Scores, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Scores)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.([]int); ok {
				t.Scores = v
				return true, nil
			}
		}
	default:
		if strings.HasPrefix(op.Path, "/label/") {
			op.Path = op.Path[len("/label/")-1:]
			return (&t.Label).applyOperation(op, logger)
		}
		if strings.HasPrefix(op.Path, "/next/") {
			if t.Next != nil {
				op.Path = op.Path[len("/next/")-1:]
				return t.Next.applyOperation(op, logger)
			}
		}
		if strings.HasPrefix(op.Path, "/children/") {
			parts := strings.Split(op.Path[len("/children/"):], "/")
			key := deep.UnescapePathKey(parts[0])
			if len(parts) == 1 {
				if !op.Strict {
					if op.Kind == deep.OpRemove {
						delete(t.Children, key)
						return true, nil
					}
					if v, ok := op.New.(*Node); ok && (op.Kind == deep.OpAdd || op.Kind == deep.OpReplace) {
						if t.Children == nil {
							t.Children = make(map[string]*Node)
						}
						t.Children[key] = v
						return true, nil
					}
				}
			} else if val, ok := t.Children[key]; ok && val != nil {
				op.Path = "/" + strings.Join(parts[1:], "/")
				return val.applyOperation(op, logger)
			}
		}
		if strings.HasPrefix(op.Path, "/links/") {
			parts := strings.Split(op.Path[len("/links/"):], "/")
			key := deep.UnescapePathKey(parts[0])
			if len(parts) == 1 && !op.Strict {
				if op.Kind == deep.OpRemove {
					delete(t.Links, key)
					return true, nil
				}
				if v, ok := op.New.(Edge); ok && (op.Kind == deep.OpAdd || op.Kind == deep.OpReplace) {
					if t.Links == nil {
						t.Links = make(map[string]Edge)
					}
					t.Links[key] = v
					return true, nil
				}
			}
		}
		if strings.HasPrefix(op.Path, "/tags/") {
			parts := strings.Split(op.Path[len("/tags/"):], "/")
			key := deep.UnescapePathKey(parts[0])
			if len(parts) == 1 && !op.Strict {
				if op.Kind == deep.OpRemove {
					delete(t.Tags, key)
					return true, nil
				}
				if v, ok := op.New.(string); ok && (op.Kind == deep.OpAdd || op.Kind == deep.OpReplace) {
					if t.Tags == nil {
						t.Tags = make(map[string]string)
					}
					t.Tags[key] = v
					return true, nil
				}
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
//
// Node values can hold two references to the same value, so a pair of
// values is diffed once, at the first path that reaches it. Every later route
// to a changed pair becomes one alias operation — "make this path hold the
// object that path holds" — appended after the rest. That keeps the patch
// linear where listing every route could be exponential, and applying it
// rebuilds the sharing whatever the target looked like before.
func (t *Node) Diff(other *Node) deep.Patch[Node] {
	seen := deep.NewDiffMemo()
	defer seen.Release()
	p := t.diffShared(other, seen, "")
	p.Operations = append(p.Operations, seen.AliasOperations()...)
	return p
}

// diffShared is Diff threaded with the pairs already visited and the absolute
// path at which t sits.
func (t *Node) diffShared(other *Node, seen *deep.DiffMemo, at string) deep.Patch[Node] {
	p := deep.Patch[Node]{}
	if t == other || !seen.Enter(t, other, at) {
		return p
	}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/name", Old: t.Name, New: other.Name})
	}
	subLabel := (&t.Label).Diff(&other.Label)
	for _, op := range subLabel.Operations {
		if op.Path == "" || op.Path == "/" {
			op.Path = at + "/label"
		} else {
			op.Path = at + "/label" + op.Path
		}
		p.Operations = append(p.Operations, op)
	}
	if t.Next == nil && other.Next != nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/next", New: other.Next})
	} else if t.Next != nil && other.Next == nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/next", Old: t.Next})
	} else if t.Next != nil && other.Next != nil {
		subNext := t.Next.diffShared(other.Next, seen, at+"/next")
		p.Operations = append(p.Operations, subNext.Operations...)
	}
	if len(t.Peers) != len(other.Peers) || (t.Peers == nil) != (other.Peers == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/peers", Old: t.Peers, New: other.Peers})
	} else {
		for i := range t.Peers {
			if (t.Peers[i] == nil) != (other.Peers[i] == nil) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + fmt.Sprintf("/peers/%d", i), Old: t.Peers[i], New: other.Peers[i]})
			} else if t.Peers[i] != nil {
				sub := t.Peers[i].diffShared(other.Peers[i], seen, at+fmt.Sprintf("/peers/%d", i))
				p.Operations = append(p.Operations, sub.Operations...)
			}
		}
	}
	if (t.Children == nil) != (other.Children == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/children", Old: t.Children, New: other.Children})
	} else {
		if other.Children != nil {
			for k, v := range other.Children {
				if t.Children == nil {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/children/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), New: v})
					continue
				}
				oldV, ok := t.Children[k]
				switch {
				case !ok:
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/children/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), New: v})
				case (oldV == nil) != (v == nil):
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/children/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: oldV, New: v})
				case oldV != nil:
					sub := oldV.diffShared(v, seen, at+"/children/"+deep.EscapePathKey(fmt.Sprintf("%v", k)))
					p.Operations = append(p.Operations, sub.Operations...)
				}
			}
		}
		if t.Children != nil {
			for k, v := range t.Children {
				if _, ok := other.Children[k]; !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/children/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: v})
				}
			}
		}
	}
	if len(t.Edges) != len(other.Edges) || (t.Edges == nil) != (other.Edges == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/edges", Old: t.Edges, New: other.Edges})
	} else {
		for i := range t.Edges {
			if !t.Edges[i].Equal(&other.Edges[i]) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + fmt.Sprintf("/edges/%d", i), Old: t.Edges[i], New: other.Edges[i]})
			}
		}
	}
	if (t.Links == nil) != (other.Links == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/links", Old: t.Links, New: other.Links})
	} else {
		if other.Links != nil {
			for k, v := range other.Links {
				if t.Links == nil {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/links/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), New: v})
					continue
				}
				if oldV, ok := t.Links[k]; !ok || !oldV.Equal(&v) {
					kind := deep.OpReplace
					if !ok {
						kind = deep.OpAdd
					}
					p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: at + "/links/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: oldV, New: v})
				}
			}
		}
		if t.Links != nil {
			for k, v := range t.Links {
				if _, ok := other.Links[k]; !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/links/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: v})
				}
			}
		}
	}
	if (t.Tags == nil) != (other.Tags == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/tags", Old: t.Tags, New: other.Tags})
	} else {
		if other.Tags != nil {
			for k, v := range other.Tags {
				if t.Tags == nil {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/tags/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), New: v})
					continue
				}
				if oldV, ok := t.Tags[k]; !ok || v != oldV {
					kind := deep.OpReplace
					if !ok {
						kind = deep.OpAdd
					}
					p.Operations = append(p.Operations, deep.Operation{Kind: kind, Path: at + "/tags/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: oldV, New: v})
				}
			}
		}
		if t.Tags != nil {
			for k, v := range t.Tags {
				if _, ok := other.Tags[k]; !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/tags/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: v})
				}
			}
		}
	}
	if len(t.Scores) != len(other.Scores) || (t.Scores == nil) != (other.Scores == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/scores", Old: t.Scores, New: other.Scores})
	} else {
		for i := range t.Scores {
			if t.Scores[i] != other.Scores[i] {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + fmt.Sprintf("/scores/%d", i), Old: t.Scores[i], New: other.Scores[i]})
			}
		}
	}

	seen.Leave(t, other, len(p.Operations))
	return p
}

func (t *Node) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/name", "/Name":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Name, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Name))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Name")
		}
		switch c.Op {
		case "==":
			return t.Name == _sv, nil
		case "!=":
			return t.Name != _sv, nil
		case ">":
			return t.Name > _sv, nil
		case "<":
			return t.Name < _sv, nil
		case ">=":
			return t.Name >= _sv, nil
		case "<=":
			return t.Name <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Name == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Name == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
//
// Node values can hold two references to the same value, so a pair of
// values is compared once however many routes lead to it, and a cycle is
// followed only until it repeats.
func (t *Node) Equal(other *Node) bool {
	seen := deep.NewVisitSet()
	defer seen.Release()
	return t.equalShared(other, seen)
}

// equalShared is Equal threaded with the set of pairs already under comparison.
func (t *Node) equalShared(other *Node, seen *deep.VisitSet) bool {
	if t == other {
		return true
	}
	if t == nil || other == nil {
		return false
	}
	if !seen.Enter(t, other) {
		// This pair has been reached before: settled if that comparison
		// finished, and a cycle if it is still running — either way there is
		// nothing left to compare here.
		return true
	}
	if t.Name != other.Name {
		return false
	}
	if !(&t.Label).Equal((&other.Label)) {
		return false
	}
	if (t.Next == nil) != (other.Next == nil) {
		return false
	}
	if t.Next != nil && !t.Next.equalShared(other.Next, seen) {
		return false
	}
	if len(t.Peers) != len(other.Peers) {
		return false
	}
	for i := range t.Peers {
		if (t.Peers[i] == nil) != (other.Peers[i] == nil) {
			return false
		}
		if t.Peers[i] != nil && !t.Peers[i].equalShared(other.Peers[i], seen) {
			return false
		}
	}
	if len(t.Children) != len(other.Children) {
		return false
	}
	for k, v := range t.Children {
		vOther, ok := other.Children[k]
		if !ok {
			return false
		}
		if (v == nil) != (vOther == nil) {
			return false
		}
		if v != nil && !v.equalShared(vOther, seen) {
			return false
		}
	}
	if len(t.Edges) != len(other.Edges) {
		return false
	}
	for i := range t.Edges {
		if !t.Edges[i].equalShared(&other.Edges[i], seen) {
			return false
		}
	}
	if len(t.Links) != len(other.Links) {
		return false
	}
	for k, v := range t.Links {
		vOther, ok := other.Links[k]
		if !ok {
			return false
		}
		_e, _o := v, vOther
		if !_e.equalShared(&_o, seen) {
			return false
		}
	}
	if len(t.Tags) != len(other.Tags) {
		return false
	}
	for k, v := range t.Tags {
		vOther, ok := other.Tags[k]
		if !ok {
			return false
		}
		if v != vOther {
			return false
		}
	}
	if len(t.Scores) != len(other.Scores) {
		return false
	}
	for i := range t.Scores {
		if t.Scores[i] != other.Scores[i] {
			return false
		}
	}
	return true
}

// Clone returns a deep copy of t.
//
// Node values can hold two references to the same value — through a
// cycle, or through two routes to one pointer — so the copy keeps track of what
// it has already copied: a value reached more than once is copied once, every
// reference to it in the result points at that one copy, and a reference cycle
// is rebuilt rather than followed forever.
func (t *Node) Clone() *Node {
	memo := deep.NewCloneMemo()
	defer memo.Release()
	return t.cloneShared(memo)
}

// cloneShared is Clone threaded with the memo of copies already made.
func (t *Node) cloneShared(memo *deep.CloneMemo) *Node {
	if t == nil {
		return nil
	}
	if done, ok := memo.Load(t); ok {
		return done.(*Node)
	}
	res := &Node{
		Name: t.Name,
	}
	// Recorded before the fields are copied, so a reference back to t from
	// anywhere below resolves to res instead of starting the copy again.
	memo.Store(t, res)
	res.Label = *(&t.Label).Clone()
	if t.Next != nil {
		res.Next = t.Next.cloneShared(memo)
	}
	if t.Peers != nil {
		res.Peers = make([]*Node, len(t.Peers))
		for i, v := range t.Peers {
			if v != nil {
				res.Peers[i] = v.cloneShared(memo)
			}
		}
	}
	if t.Children != nil {
		res.Children = make(map[string]*Node)
		for k, v := range t.Children {
			if v != nil {
				res.Children[k] = v.cloneShared(memo)
			}
		}
	}
	if t.Edges != nil {
		res.Edges = make([]Edge, len(t.Edges))
		for i := range t.Edges {
			res.Edges[i] = *t.Edges[i].cloneShared(memo)
		}
	}
	if t.Links != nil {
		res.Links = make(map[string]Edge)
		for k, v := range t.Links {
			_e := v
			res.Links[k] = *_e.cloneShared(memo)
		}
	}
	if t.Tags != nil {
		res.Tags = make(map[string]string)
		for k, v := range t.Tags {
			res.Tags[k] = v
		}
	}
	if t.Scores != nil {
		res.Scores = make([]int, len(t.Scores))
		copy(res.Scores, t.Scores)
	}
	return res
}
