// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"log/slog"
	deep "github.com/brunoga/deep/v5"
	"reflect"
	"regexp"
)

// ApplyOperation applies a single operation to Employee efficiently.
func (t *Employee) ApplyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.EvaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.EvaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(Employee); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(deep.Operation{Kind: op.Kind, Path: "/" + k, New: v}, logger)
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/id", "/ID":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.ID)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			_oldOK := false
			if _oldV, ok := op.Old.(int); ok {
				_oldOK = t.ID == _oldV
			}
			if !_oldOK {
				if _oldF, ok := op.Old.(float64); ok {
					_oldOK = float64(t.ID) == _oldF
				}
			}
			if !_oldOK {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.ID)
			}
		}
		if v, ok := op.New.(int); ok {
			t.ID = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.ID = int(f)
			return true, nil
		}
	case "/name", "/Name":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Name)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Name != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Name = v
			return true, nil
		}
	case "/role", "/Role":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Role)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Role != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Role)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Role = v
			return true, nil
		}
	case "/rating", "/Rating":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Rating)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			_oldOK := false
			if _oldV, ok := op.Old.(int); ok {
				_oldOK = t.Rating == _oldV
			}
			if !_oldOK {
				if _oldF, ok := op.Old.(float64); ok {
					_oldOK = float64(t.Rating) == _oldF
				}
			}
			if !_oldOK {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Rating)
			}
		}
		if v, ok := op.New.(int); ok {
			t.Rating = v
			return true, nil
		}
		if f, ok := op.New.(float64); ok {
			t.Rating = int(f)
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Employee) Diff(other *Employee) deep.Patch[Employee] {
	p := deep.Patch[Employee]{}
	if t.ID != other.ID {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/id", Old: t.ID, New: other.ID})
	}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/name", Old: t.Name, New: other.Name})
	}
	if t.Role != other.Role {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/role", Old: t.Role, New: other.Role})
	}
	if t.Rating != other.Rating {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/rating", Old: t.Rating, New: other.Rating})
	}

	return p
}

func (t *Employee) EvaluateCondition(c deep.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.EvaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.EvaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.EvaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/id", "/ID":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.ID, c.Value.(string)), nil
		}
		if c.Op == "log" {
			slog.Default().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.ID)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.ID))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field ID")
		}
		_fv := float64(t.ID)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.ID == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.ID == iv {
							return true, nil
						}
					case float64:
						if float64(t.ID) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/name", "/Name":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Name, c.Value.(string)), nil
		}
		if c.Op == "log" {
			slog.Default().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Name)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Name))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Name")
		}
		switch c.Op {
		case "==":
			return t.Name == _sv, nil
		case "!=":
			return t.Name != _sv, nil
		case ">":
			return t.Name > _sv, nil
		case "<":
			return t.Name < _sv, nil
		case ">=":
			return t.Name >= _sv, nil
		case "<=":
			return t.Name <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Name == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Name == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/role", "/Role":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Role, c.Value.(string)), nil
		}
		if c.Op == "log" {
			slog.Default().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Role)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Role))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Role")
		}
		switch c.Op {
		case "==":
			return t.Role == _sv, nil
		case "!=":
			return t.Role != _sv, nil
		case ">":
			return t.Role > _sv, nil
		case "<":
			return t.Role < _sv, nil
		case ">=":
			return t.Role >= _sv, nil
		case "<=":
			return t.Role <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Role == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Role == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/rating", "/Rating":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return checkType(t.Rating, c.Value.(string)), nil
		}
		if c.Op == "log" {
			slog.Default().Info("deep condition log", "message", c.Value, "path", c.Path, "value", t.Rating)
			return true, nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Rating))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Rating")
		}
		_fv := float64(t.Rating)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Rating == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Rating == iv {
							return true, nil
						}
					case float64:
						if float64(t.Rating) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *Employee) Equal(other *Employee) bool {
	if t.ID != other.ID {
		return false
	}
	if t.Name != other.Name {
		return false
	}
	if t.Role != other.Role {
		return false
	}
	if t.Rating != other.Rating {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *Employee) Copy() *Employee {
	res := &Employee{
		ID:     t.ID,
		Name:   t.Name,
		Role:   t.Role,
		Rating: t.Rating,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}

func checkType(v any, typeName string) bool {
	switch typeName {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		switch v.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
			return true
		}
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Struct || rv.Kind() == reflect.Map
	case "array":
		rv := reflect.ValueOf(v)
		return rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array
	case "null":
		if v == nil {
			return true
		}
		rv := reflect.ValueOf(v)
		return (rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface ||
			rv.Kind() == reflect.Slice || rv.Kind() == reflect.Map) && rv.IsNil()
	}
	return false
}
