// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	"github.com/brunoga/deep/v5"
)

// ApplyOperation applies a single operation to UIState efficiently.
func (t *UIState) ApplyOperation(op v5.Operation) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, err
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err == nil && ok {
			return true, nil
		}
	}

	if op.Path == "" || op.Path == "/" {
		if v, ok := op.New.(UIState); ok {
			*t = v
			return true, nil
		}
		if m, ok := op.New.(map[string]any); ok {
			for k, v := range m {
				t.ApplyOperation(v5.Operation{Kind: op.Kind, Path: "/" + k, New: v})
			}
			return true, nil
		}
	}

	switch op.Path {
	case "/theme", "/Theme":
		if v, ok := op.New.(string); ok {
			t.Theme = v
			return true, nil
		}
	case "/sidebar_open", "/Open":
		if v, ok := op.New.(bool); ok {
			t.Open = v
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *UIState) Diff(other *UIState) v5.Patch[UIState] {
	p := v5.NewPatch[UIState]()
	if t.Theme != other.Theme {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/theme",
			Old:  t.Theme,
			New:  other.Theme,
		})
	}
	if t.Open != other.Open {
		p.Operations = append(p.Operations, v5.Operation{
			Kind: v5.OpReplace,
			Path: "/sidebar_open",
			Old:  t.Open,
			New:  other.Open,
		})
	}
	return p
}

func (t *UIState) evaluateCondition(c v5.Condition) (bool, error) {
	switch c.Path {
	case "/theme", "/Theme":
		switch c.Op {
		case "==":
			return t.Theme == c.Value.(string), nil
		case "!=":
			return t.Theme != c.Value.(string), nil
		}
	case "/sidebar_open", "/Open":
		switch c.Op {
		case "==":
			return t.Open == c.Value.(bool), nil
		case "!=":
			return t.Open != c.Value.(bool), nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *UIState) Equal(other *UIState) bool {
	if t.Theme != other.Theme {
		return false
	}
	if t.Open != other.Open {
		return false
	}
	return true
}

// Copy returns a deep copy of t.
func (t *UIState) Copy() *UIState {
	res := &UIState{
		Theme: t.Theme,
		Open:  t.Open,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
