// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	core "github.com/brunoga/deep/v5/core"
	"log/slog"
	"regexp"
)

// Patch applies p to t using the generated fast path.
func (t *UIState) Patch(p deep.Patch[UIState], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := deep.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *UIState) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil || !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil || ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			if !deep.Equal(*t, op.Old.(UIState)) {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(UIState); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/theme", "/Theme":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Theme)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(string); !ok || t.Theme != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Theme)
			}
		}
		if v, ok := op.New.(string); ok {
			t.Theme = v
			return true, nil
		}
	case "/sidebar_open", "/Open":
		if op.Kind == deep.OpLog {
			logger.Info("deep log", "message", op.New, "path", op.Path, "field", t.Open)
			return true, nil
		}
		if op.Kind == deep.OpReplace && op.Strict {
			if _oldV, ok := op.Old.(bool); !ok || t.Open != _oldV {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Open)
			}
		}
		if v, ok := op.New.(bool); ok {
			t.Open = v
			return true, nil
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *UIState) Diff(other *UIState) deep.Patch[UIState] {
	p := deep.Patch[UIState]{}
	if t.Theme != other.Theme {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/theme", Old: t.Theme, New: other.Theme})
	}
	if t.Open != other.Open {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/sidebar_open", Old: t.Open, New: other.Open})
	}

	return p
}

func (t *UIState) evaluateCondition(c core.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/theme", "/Theme":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return core.CheckType(t.Theme, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Theme))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Theme")
		}
		switch c.Op {
		case "==":
			return t.Theme == _sv, nil
		case "!=":
			return t.Theme != _sv, nil
		case ">":
			return t.Theme > _sv, nil
		case "<":
			return t.Theme < _sv, nil
		case ">=":
			return t.Theme >= _sv, nil
		case "<=":
			return t.Theme <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Theme == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Theme == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/sidebar_open", "/Open":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			return core.CheckType(t.Open, c.Value.(string)), nil
		}
		if c.Op == "matches" {
			return regexp.MatchString(c.Value.(string), fmt.Sprintf("%v", t.Open))
		}
		_bv, _ok := c.Value.(bool)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Open")
		}
		switch c.Op {
		case "==":
			return t.Open == _bv, nil
		case "!=":
			return t.Open != _bv, nil
		}
	}
	return false, fmt.Errorf("unsupported condition path or op: %s", c.Path)
}

// Equal returns true if t and other are deeply equal.
func (t *UIState) Equal(other *UIState) bool {
	if t.Theme != other.Theme {
		return false
	}
	if t.Open != other.Open {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *UIState) Clone() *UIState {
	res := &UIState{
		Theme: t.Theme,
		Open:  t.Open,
	}
	return res
}

func contains[M ~map[K]V, K comparable, V any](m M, k K) bool {
	_, ok := m[k]
	return ok
}
