// Code generated by deep-gen. DO NOT EDIT.
package record

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	gen "github.com/brunoga/deep/v5/gen"
	"log/slog"
	"reflect"
	"regexp"
)

// Patch applies p to t using the generated fast path.
func (t *Record) Patch(p deep.Patch[Record], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Record) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Record); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Record); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/id", "/ID":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.ID == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.ID, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.ID)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.ID = v
				return true, nil
			}
		}
	case "/version", "/Version":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Version == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Version, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Version)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Version = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Version = int(f)
				return true, nil
			}
		}
	case "/stock", "/Stock":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Stock == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Stock, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Stock)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Stock = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Stock = int(f)
				return true, nil
			}
		}
	case "/price", "/Price":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Price == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Price, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Price)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Price = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Price = int(f)
				return true, nil
			}
		}
	case "/views", "/Views":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Views == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Views, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Views)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Views = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Views = int(f)
				return true, nil
			}
		}
	case "/rating", "/Rating":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Rating == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Rating, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Rating)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Rating = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Rating = int(f)
				return true, nil
			}
		}
	case "/reserved", "/Reserved":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Reserved == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Reserved, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Reserved)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Reserved = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Reserved = int(f)
				return true, nil
			}
		}
	case "/shipped", "/Shipped":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Shipped == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Shipped, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Shipped)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Shipped = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Shipped = int(f)
				return true, nil
			}
		}
	case "/returned", "/Returned":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Returned == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Returned, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Returned)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Returned = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Returned = int(f)
				return true, nil
			}
		}
	case "/flagged", "/Flagged":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(int); ok {
				_match = t.Flagged == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Flagged, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Flagged)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(int); ok {
				t.Flagged = v
				return true, nil
			}
			if f, ok := op.New.(float64); ok {
				t.Flagged = int(f)
				return true, nil
			}
		}
	default:
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
func (t *Record) Diff(other *Record) deep.Patch[Record] {
	p := deep.Patch[Record]{}
	if t.ID != other.ID {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/id", Old: t.ID, New: other.ID})
	}
	if t.Version != other.Version {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/version", Old: t.Version, New: other.Version})
	}
	if t.Stock != other.Stock {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/stock", Old: t.Stock, New: other.Stock})
	}
	if t.Price != other.Price {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/price", Old: t.Price, New: other.Price})
	}
	if t.Views != other.Views {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/views", Old: t.Views, New: other.Views})
	}
	if t.Rating != other.Rating {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/rating", Old: t.Rating, New: other.Rating})
	}
	if t.Reserved != other.Reserved {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/reserved", Old: t.Reserved, New: other.Reserved})
	}
	if t.Shipped != other.Shipped {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/shipped", Old: t.Shipped, New: other.Shipped})
	}
	if t.Returned != other.Returned {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/returned", Old: t.Returned, New: other.Returned})
	}
	if t.Flagged != other.Flagged {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: "/flagged", Old: t.Flagged, New: other.Flagged})
	}

	return p
}

func (t *Record) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/id", "/ID":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.ID, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.ID))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field ID")
		}
		switch c.Op {
		case "==":
			return t.ID == _sv, nil
		case "!=":
			return t.ID != _sv, nil
		case ">":
			return t.ID > _sv, nil
		case "<":
			return t.ID < _sv, nil
		case ">=":
			return t.ID >= _sv, nil
		case "<=":
			return t.ID <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.ID == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.ID == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	case "/version", "/Version":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Version, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Version))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Version")
		}
		_fv := float64(t.Version)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Version == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Version == iv {
							return true, nil
						}
					case float64:
						if float64(t.Version) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/stock", "/Stock":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Stock, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Stock))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Stock")
		}
		_fv := float64(t.Stock)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Stock == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Stock == iv {
							return true, nil
						}
					case float64:
						if float64(t.Stock) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/price", "/Price":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Price, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Price))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Price")
		}
		_fv := float64(t.Price)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Price == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Price == iv {
							return true, nil
						}
					case float64:
						if float64(t.Price) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/views", "/Views":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Views, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Views))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Views")
		}
		_fv := float64(t.Views)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Views == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Views == iv {
							return true, nil
						}
					case float64:
						if float64(t.Views) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/rating", "/Rating":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Rating, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Rating))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Rating")
		}
		_fv := float64(t.Rating)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Rating == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Rating == iv {
							return true, nil
						}
					case float64:
						if float64(t.Rating) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/reserved", "/Reserved":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Reserved, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Reserved))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Reserved")
		}
		_fv := float64(t.Reserved)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Reserved == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Reserved == iv {
							return true, nil
						}
					case float64:
						if float64(t.Reserved) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/shipped", "/Shipped":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Shipped, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Shipped))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Shipped")
		}
		_fv := float64(t.Shipped)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Shipped == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Shipped == iv {
							return true, nil
						}
					case float64:
						if float64(t.Shipped) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/returned", "/Returned":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Returned, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Returned))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Returned")
		}
		_fv := float64(t.Returned)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Returned == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Returned == iv {
							return true, nil
						}
					case float64:
						if float64(t.Returned) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	case "/flagged", "/Flagged":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Flagged, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Flagged))
		}
		var _cv float64
		switch v := c.Value.(type) {
		case int:
			_cv = float64(v)
		case float64:
			_cv = v
		default:
			return false, fmt.Errorf("condition value type mismatch for field Flagged")
		}
		_fv := float64(t.Flagged)
		switch c.Op {
		case "==":
			return _fv == _cv, nil
		case "!=":
			return _fv != _cv, nil
		case ">":
			return _fv > _cv, nil
		case "<":
			return _fv < _cv, nil
		case ">=":
			return _fv >= _cv, nil
		case "<=":
			return _fv <= _cv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []int:
				for _, v := range vals {
					if t.Flagged == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					switch iv := v.(type) {
					case int:
						if t.Flagged == iv {
							return true, nil
						}
					case float64:
						if float64(t.Flagged) == iv {
							return true, nil
						}
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
func (t *Record) Equal(other *Record) bool {
	if t.ID != other.ID {
		return false
	}
	if t.Version != other.Version {
		return false
	}
	if t.Stock != other.Stock {
		return false
	}
	if t.Price != other.Price {
		return false
	}
	if t.Views != other.Views {
		return false
	}
	if t.Rating != other.Rating {
		return false
	}
	if t.Reserved != other.Reserved {
		return false
	}
	if t.Shipped != other.Shipped {
		return false
	}
	if t.Returned != other.Returned {
		return false
	}
	if t.Flagged != other.Flagged {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
func (t *Record) Clone() *Record {
	res := &Record{
		ID:       t.ID,
		Version:  t.Version,
		Stock:    t.Stock,
		Price:    t.Price,
		Views:    t.Views,
		Rating:   t.Rating,
		Reserved: t.Reserved,
		Shipped:  t.Shipped,
		Returned: t.Returned,
		Flagged:  t.Flagged,
	}
	return res
}
