// Code generated by deep-gen. DO NOT EDIT.
package main

import (
	"fmt"
	deep "github.com/brunoga/deep/v5"
	"github.com/brunoga/deep/v5/condition"
	gen "github.com/brunoga/deep/v5/gen"
	"log/slog"
	"reflect"
	"regexp"
	"strings"
)

// Patch applies p to t using the generated fast path.
func (t *Person) Patch(p deep.Patch[Person], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Person) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Person); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Person); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/name", "/Name":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Name == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Name, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Name = v
				return true, nil
			}
		}
	case "/team", "/Team":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(*Team); ok {
				_match = deep.Equal(t.Team, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Team, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Team)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(*Team); ok {
				t.Team = v
				return true, nil
			}
		}
	case "/manager", "/Manager":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(*Person); ok {
				_match = deep.Equal(t.Manager, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Manager, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Manager)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(*Person); ok {
				t.Manager = v
				return true, nil
			}
		}
	default:
		if strings.HasPrefix(op.Path, "/team/") {
			if t.Team != nil {
				op.Path = op.Path[len("/team/")-1:]
				return t.Team.applyOperation(op, logger)
			}
		}
		if strings.HasPrefix(op.Path, "/manager/") {
			if t.Manager != nil {
				op.Path = op.Path[len("/manager/")-1:]
				return t.Manager.applyOperation(op, logger)
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
//
// Person values can hold two references to the same value, so a pair of
// values is diffed once, at the first path that reaches it. Every later route
// to a changed pair becomes one alias operation — "make this path hold the
// object that path holds" — appended after the rest. That keeps the patch
// linear where listing every route could be exponential, and applying it
// rebuilds the sharing whatever the target looked like before.
func (t *Person) Diff(other *Person) deep.Patch[Person] {
	seen := gen.NewDiffMemo()
	defer seen.Release()
	p := t.diffShared(other, seen, "")
	p.Operations = append(p.Operations, seen.AliasOperations()...)
	return p
}

// diffShared is Diff threaded with the pairs already visited and the absolute
// path at which t sits.
func (t *Person) diffShared(other *Person, seen *gen.DiffMemo, at string) deep.Patch[Person] {
	p := deep.Patch[Person]{}
	if t == other || !seen.Enter(t, other, at) {
		return p
	}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/name", Old: t.Name, New: other.Name})
	}
	if t.Team == nil && other.Team != nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/team", New: other.Team})
	} else if t.Team != nil && other.Team == nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/team", Old: t.Team})
	} else if t.Team != nil && other.Team != nil {
		subTeam := t.Team.diffShared(other.Team, seen, at+"/team")
		p.Operations = append(p.Operations, subTeam.Operations...)
	}
	if t.Manager == nil && other.Manager != nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/manager", New: other.Manager})
	} else if t.Manager != nil && other.Manager == nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/manager", Old: t.Manager})
	} else if t.Manager != nil && other.Manager != nil {
		subManager := t.Manager.diffShared(other.Manager, seen, at+"/manager")
		p.Operations = append(p.Operations, subManager.Operations...)
	}

	seen.Leave(t, other, len(p.Operations))
	return p
}

func (t *Person) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/name", "/Name":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Name, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Name))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Name")
		}
		switch c.Op {
		case "==":
			return t.Name == _sv, nil
		case "!=":
			return t.Name != _sv, nil
		case ">":
			return t.Name > _sv, nil
		case "<":
			return t.Name < _sv, nil
		case ">=":
			return t.Name >= _sv, nil
		case "<=":
			return t.Name <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Name == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Name == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
//
// Person values can hold two references to the same value, so a pair of
// values is compared once however many routes lead to it, and a cycle is
// followed only until it repeats.
func (t *Person) Equal(other *Person) bool {
	seen := gen.NewVisitSet()
	defer seen.Release()
	return t.equalShared(other, seen)
}

// equalShared is Equal threaded with the set of pairs already under comparison.
func (t *Person) equalShared(other *Person, seen *gen.VisitSet) bool {
	if t == other {
		return true
	}
	if t == nil || other == nil {
		return false
	}
	if !seen.Enter(t, other) {
		// This pair has been reached before: settled if that comparison
		// finished, and a cycle if it is still running — either way there is
		// nothing left to compare here.
		return true
	}
	if t.Name != other.Name {
		return false
	}
	if (t.Team == nil) != (other.Team == nil) {
		return false
	}
	if t.Team != nil && !t.Team.equalShared(other.Team, seen) {
		return false
	}
	if (t.Manager == nil) != (other.Manager == nil) {
		return false
	}
	if t.Manager != nil && !t.Manager.equalShared(other.Manager, seen) {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
//
// Person values can hold two references to the same value — through a
// cycle, or through two routes to one pointer — so the copy keeps track of what
// it has already copied: a value reached more than once is copied once, every
// reference to it in the result points at that one copy, and a reference cycle
// is rebuilt rather than followed forever.
func (t *Person) Clone() *Person {
	memo := gen.NewCloneMemo()
	defer memo.Release()
	return t.cloneShared(memo)
}

// cloneShared is Clone threaded with the memo of copies already made.
func (t *Person) cloneShared(memo *gen.CloneMemo) *Person {
	if t == nil {
		return nil
	}
	if done, ok := memo.Load(t); ok {
		return done.(*Person)
	}
	res := &Person{
		Name: t.Name,
	}
	// Recorded before the fields are copied, so a reference back to t from
	// anywhere below resolves to res instead of starting the copy again.
	memo.Store(t, res)
	if t.Team != nil {
		res.Team = t.Team.cloneShared(memo)
	}
	if t.Manager != nil {
		res.Manager = t.Manager.cloneShared(memo)
	}
	return res
}

// Patch applies p to t using the generated fast path.
func (t *Team) Patch(p deep.Patch[Team], logger *slog.Logger) error {
	if logger == nil {
		logger = slog.Default()
	}
	if p.Guard != nil {
		ok, err := t.evaluateCondition(*p.Guard)
		if err != nil {
			return fmt.Errorf("global condition evaluation failed: %w", err)
		}
		if !ok {
			return fmt.Errorf("global condition not met")
		}
	}
	var errs []error
	for _, op := range p.Operations {
		op.Strict = p.Strict
		handled, err := t.applyOperation(op, logger)
		if err != nil {
			errs = append(errs, err)
		} else if !handled {
			if err := gen.ApplyOpReflection(t, op, logger); err != nil {
				errs = append(errs, err)
			}
		}
	}
	if len(errs) > 0 {
		return &deep.ApplyError{Errors: errs}
	}
	return nil
}

func (t *Team) applyOperation(op deep.Operation, logger *slog.Logger) (bool, error) {
	if op.If != nil {
		ok, err := t.evaluateCondition(*op.If)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if !ok {
			return true, nil
		}
	}
	if op.Unless != nil {
		ok, err := t.evaluateCondition(*op.Unless)
		if err != nil {
			return true, fmt.Errorf("condition evaluation failed at %s: %w", op.Path, err)
		}
		if ok {
			return true, nil
		}
	}
	if op.Kind == deep.OpLog {
		logger.Info("deep log", "message", op.New, "path", op.Path)
		return true, nil
	}

	switch op.Path {
	case "/":
		if op.Strict && op.Old != nil && (op.Kind == deep.OpReplace || op.Kind == deep.OpRemove) {
			_match := false
			if old, ok := op.Old.(Team); ok {
				_match = deep.Equal(*t, old)
			}
			if !_match {
				_match = deep.EqualCoerced(*t, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at root: expected %v, got %v", op.Old, *t)
			}
		}
		if op.Kind == deep.OpReplace {
			if v, ok := op.New.(Team); ok {
				*t = v
				return true, nil
			}
		}
		return true, fmt.Errorf("unsupported root operation: %s", op.Kind)
	case "/name", "/Name":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if _oldV, ok := op.Old.(string); ok {
				_match = t.Name == _oldV
			}
			if !_match {
				_match = deep.EqualCoerced(t.Name, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Name)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(string); ok {
				t.Name = v
				return true, nil
			}
		}
	case "/members", "/Members":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.([]*Person); ok {
				_match = deep.Equal(t.Members, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Members, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Members)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.([]*Person); ok {
				t.Members = v
				return true, nil
			}
		}
	case "/byName", "/ByName":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(map[string]*Person); ok {
				_match = deep.Equal(t.ByName, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.ByName, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.ByName)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(map[string]*Person); ok {
				t.ByName = v
				return true, nil
			}
		}
	case "/lead", "/Lead":
		if op.Kind == deep.OpReplace && op.Strict && op.Old != nil {
			_match := false
			if old, ok := op.Old.(*Person); ok {
				_match = deep.Equal(t.Lead, old)
			}
			if !_match {
				_match = deep.EqualCoerced(t.Lead, op.Old)
			}
			if !_match {
				return true, fmt.Errorf("strict check failed at %s: expected %v, got %v", op.Path, op.Old, t.Lead)
			}
		}
		if op.Kind == deep.OpAdd || op.Kind == deep.OpReplace {
			if v, ok := op.New.(*Person); ok {
				t.Lead = v
				return true, nil
			}
		}
	default:
		if strings.HasPrefix(op.Path, "/byName/") {
			parts := strings.Split(op.Path[len("/byName/"):], "/")
			key := deep.UnescapePathKey(parts[0])
			if len(parts) == 1 {
				if !op.Strict {
					if op.Kind == deep.OpRemove {
						delete(t.ByName, key)
						return true, nil
					}
					if v, ok := op.New.(*Person); ok && (op.Kind == deep.OpAdd || op.Kind == deep.OpReplace) {
						if t.ByName == nil {
							t.ByName = make(map[string]*Person)
						}
						t.ByName[key] = v
						return true, nil
					}
				}
			} else if val, ok := t.ByName[key]; ok && val != nil {
				op.Path = "/" + strings.Join(parts[1:], "/")
				return val.applyOperation(op, logger)
			}
		}
		if strings.HasPrefix(op.Path, "/lead/") {
			if t.Lead != nil {
				op.Path = op.Path[len("/lead/")-1:]
				return t.Lead.applyOperation(op, logger)
			}
		}
	}
	return false, nil
}

// Diff compares t with other and returns a Patch.
//
// Team values can hold two references to the same value, so a pair of
// values is diffed once, at the first path that reaches it. Every later route
// to a changed pair becomes one alias operation — "make this path hold the
// object that path holds" — appended after the rest. That keeps the patch
// linear where listing every route could be exponential, and applying it
// rebuilds the sharing whatever the target looked like before.
func (t *Team) Diff(other *Team) deep.Patch[Team] {
	seen := gen.NewDiffMemo()
	defer seen.Release()
	p := t.diffShared(other, seen, "")
	p.Operations = append(p.Operations, seen.AliasOperations()...)
	return p
}

// diffShared is Diff threaded with the pairs already visited and the absolute
// path at which t sits.
func (t *Team) diffShared(other *Team, seen *gen.DiffMemo, at string) deep.Patch[Team] {
	p := deep.Patch[Team]{}
	if t == other || !seen.Enter(t, other, at) {
		return p
	}
	if t.Name != other.Name {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/name", Old: t.Name, New: other.Name})
	}
	if len(t.Members) != len(other.Members) || (t.Members == nil) != (other.Members == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/members", Old: t.Members, New: other.Members})
	} else {
		for i := range t.Members {
			if (t.Members[i] == nil) != (other.Members[i] == nil) {
				p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + fmt.Sprintf("/members/%d", i), Old: t.Members[i], New: other.Members[i]})
			} else if t.Members[i] != nil {
				sub := t.Members[i].diffShared(other.Members[i], seen, at+fmt.Sprintf("/members/%d", i))
				p.Operations = append(p.Operations, sub.Operations...)
			}
		}
	}
	if (t.ByName == nil) != (other.ByName == nil) {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/byName", Old: t.ByName, New: other.ByName})
	} else {
		if other.ByName != nil {
			for _, k := range gen.SortedKeys(other.ByName) {
				v := other.ByName[k]
				if t.ByName == nil {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/byName/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), New: v})
					continue
				}
				oldV, ok := t.ByName[k]
				switch {
				case !ok:
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/byName/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), New: v})
				case (oldV == nil) != (v == nil):
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpReplace, Path: at + "/byName/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: oldV, New: v})
				case oldV != nil:
					sub := oldV.diffShared(v, seen, at+"/byName/"+deep.EscapePathKey(fmt.Sprintf("%v", k)))
					p.Operations = append(p.Operations, sub.Operations...)
				}
			}
		}
		if t.ByName != nil {
			for _, k := range gen.SortedKeys(t.ByName) {
				v := t.ByName[k]
				if _, ok := other.ByName[k]; !ok {
					p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/byName/" + deep.EscapePathKey(fmt.Sprintf("%v", k)), Old: v})
				}
			}
		}
	}
	if t.Lead == nil && other.Lead != nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpAdd, Path: at + "/lead", New: other.Lead})
	} else if t.Lead != nil && other.Lead == nil {
		p.Operations = append(p.Operations, deep.Operation{Kind: deep.OpRemove, Path: at + "/lead", Old: t.Lead})
	} else if t.Lead != nil && other.Lead != nil {
		subLead := t.Lead.diffShared(other.Lead, seen, at+"/lead")
		p.Operations = append(p.Operations, subLead.Operations...)
	}

	seen.Leave(t, other, len(p.Operations))
	return p
}

func (t *Team) evaluateCondition(c condition.Condition) (bool, error) {
	switch c.Op {
	case "and":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err != nil || !ok {
				return false, err
			}
		}
		return true, nil
	case "or":
		for _, sub := range c.Sub {
			ok, err := t.evaluateCondition(*sub)
			if err == nil && ok {
				return true, nil
			}
		}
		return false, nil
	case "not":
		if len(c.Sub) > 0 {
			ok, err := t.evaluateCondition(*c.Sub[0])
			if err != nil {
				return false, err
			}
			return !ok, nil
		}
		return true, nil
	}

	switch c.Path {
	case "/name", "/Name":
		if c.Op == "exists" {
			return true, nil
		}
		if c.Op == "type" {
			tn, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("type requires string value")
			}
			return condition.CheckType(t.Name, tn), nil
		}
		if c.Op == "matches" {
			pat, ok := c.Value.(string)
			if !ok {
				return false, fmt.Errorf("matches requires string pattern")
			}
			return regexp.MatchString(pat, fmt.Sprintf("%v", t.Name))
		}
		_sv, _ok := c.Value.(string)
		if !_ok {
			return false, fmt.Errorf("condition value type mismatch for field Name")
		}
		switch c.Op {
		case "==":
			return t.Name == _sv, nil
		case "!=":
			return t.Name != _sv, nil
		case ">":
			return t.Name > _sv, nil
		case "<":
			return t.Name < _sv, nil
		case ">=":
			return t.Name >= _sv, nil
		case "<=":
			return t.Name <= _sv, nil
		case "in":
			switch vals := c.Value.(type) {
			case []string:
				for _, v := range vals {
					if t.Name == v {
						return true, nil
					}
				}
			case []any:
				for _, v := range vals {
					if sv, ok := v.(string); ok && t.Name == sv {
						return true, nil
					}
				}
			}
			return false, nil
		}
	}
	// Anything the fast path does not model — nested paths, collection
	// lookups, unusual ops — is evaluated by the reflection engine, which
	// handles the full condition language.
	return condition.Evaluate(reflect.ValueOf(t).Elem(), &c)
}

// Equal returns true if t and other are deeply equal.
//
// Team values can hold two references to the same value, so a pair of
// values is compared once however many routes lead to it, and a cycle is
// followed only until it repeats.
func (t *Team) Equal(other *Team) bool {
	seen := gen.NewVisitSet()
	defer seen.Release()
	return t.equalShared(other, seen)
}

// equalShared is Equal threaded with the set of pairs already under comparison.
func (t *Team) equalShared(other *Team, seen *gen.VisitSet) bool {
	if t == other {
		return true
	}
	if t == nil || other == nil {
		return false
	}
	if !seen.Enter(t, other) {
		// This pair has been reached before: settled if that comparison
		// finished, and a cycle if it is still running — either way there is
		// nothing left to compare here.
		return true
	}
	if t.Name != other.Name {
		return false
	}
	if len(t.Members) != len(other.Members) {
		return false
	}
	for i := range t.Members {
		if (t.Members[i] == nil) != (other.Members[i] == nil) {
			return false
		}
		if t.Members[i] != nil && !t.Members[i].equalShared(other.Members[i], seen) {
			return false
		}
	}
	if len(t.ByName) != len(other.ByName) {
		return false
	}
	for k, v := range t.ByName {
		vOther, ok := other.ByName[k]
		if !ok {
			return false
		}
		if (v == nil) != (vOther == nil) {
			return false
		}
		if v != nil && !v.equalShared(vOther, seen) {
			return false
		}
	}
	if (t.Lead == nil) != (other.Lead == nil) {
		return false
	}
	if t.Lead != nil && !t.Lead.equalShared(other.Lead, seen) {
		return false
	}
	return true
}

// Clone returns a deep copy of t.
//
// Team values can hold two references to the same value — through a
// cycle, or through two routes to one pointer — so the copy keeps track of what
// it has already copied: a value reached more than once is copied once, every
// reference to it in the result points at that one copy, and a reference cycle
// is rebuilt rather than followed forever.
func (t *Team) Clone() *Team {
	memo := gen.NewCloneMemo()
	defer memo.Release()
	return t.cloneShared(memo)
}

// cloneShared is Clone threaded with the memo of copies already made.
func (t *Team) cloneShared(memo *gen.CloneMemo) *Team {
	if t == nil {
		return nil
	}
	if done, ok := memo.Load(t); ok {
		return done.(*Team)
	}
	res := &Team{
		Name: t.Name,
	}
	// Recorded before the fields are copied, so a reference back to t from
	// anywhere below resolves to res instead of starting the copy again.
	memo.Store(t, res)
	if t.Members != nil {
		res.Members = make([]*Person, len(t.Members))
		for i, v := range t.Members {
			if v != nil {
				res.Members[i] = v.cloneShared(memo)
			}
		}
	}
	if t.ByName != nil {
		res.ByName = make(map[string]*Person)
		for k, v := range t.ByName {
			if v != nil {
				res.ByName[k] = v.cloneShared(memo)
			}
		}
	}
	if t.Lead != nil {
		res.Lead = t.Lead.cloneShared(memo)
	}
	return res
}
